package com.example.sms.infrastructure.datasource.master.product;

import java.time.LocalDateTime;
import java.util.List;

public class 商品分類マスタ {
    private List<商品マスタ> 商品マスタ;

    public List<商品マスタ> get商品マスタ() {
        return 商品マスタ;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品分類マスタ.商品分類コード
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private String 商品分類コード;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品分類マスタ.商品分類名
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private String 商品分類名;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品分類マスタ.商品分類階層
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private Integer 商品分類階層;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品分類マスタ.商品分類パス
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private String 商品分類パス;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品分類マスタ.最下層区分
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private Integer 最下層区分;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品分類マスタ.作成日時
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private LocalDateTime 作成日時;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品分類マスタ.作成者名
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private String 作成者名;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品分類マスタ.更新日時
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private LocalDateTime 更新日時;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品分類マスタ.更新者名
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private String 更新者名;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品分類マスタ.商品分類コード
     *
     * @return the value of public.商品分類マスタ.商品分類コード
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public String get商品分類コード() {
        return 商品分類コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品分類マスタ.商品分類コード
     *
     * @param 商品分類コード the value for public.商品分類マスタ.商品分類コード
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set商品分類コード(String 商品分類コード) {
        this.商品分類コード = 商品分類コード == null ? null : 商品分類コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品分類マスタ.商品分類名
     *
     * @return the value of public.商品分類マスタ.商品分類名
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public String get商品分類名() {
        return 商品分類名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品分類マスタ.商品分類名
     *
     * @param 商品分類名 the value for public.商品分類マスタ.商品分類名
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set商品分類名(String 商品分類名) {
        this.商品分類名 = 商品分類名 == null ? null : 商品分類名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品分類マスタ.商品分類階層
     *
     * @return the value of public.商品分類マスタ.商品分類階層
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public Integer get商品分類階層() {
        return 商品分類階層;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品分類マスタ.商品分類階層
     *
     * @param 商品分類階層 the value for public.商品分類マスタ.商品分類階層
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set商品分類階層(Integer 商品分類階層) {
        this.商品分類階層 = 商品分類階層;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品分類マスタ.商品分類パス
     *
     * @return the value of public.商品分類マスタ.商品分類パス
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public String get商品分類パス() {
        return 商品分類パス;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品分類マスタ.商品分類パス
     *
     * @param 商品分類パス the value for public.商品分類マスタ.商品分類パス
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set商品分類パス(String 商品分類パス) {
        this.商品分類パス = 商品分類パス == null ? null : 商品分類パス.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品分類マスタ.最下層区分
     *
     * @return the value of public.商品分類マスタ.最下層区分
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public Integer get最下層区分() {
        return 最下層区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品分類マスタ.最下層区分
     *
     * @param 最下層区分 the value for public.商品分類マスタ.最下層区分
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set最下層区分(Integer 最下層区分) {
        this.最下層区分 = 最下層区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品分類マスタ.作成日時
     *
     * @return the value of public.商品分類マスタ.作成日時
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品分類マスタ.作成日時
     *
     * @param 作成日時 the value for public.商品分類マスタ.作成日時
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品分類マスタ.作成者名
     *
     * @return the value of public.商品分類マスタ.作成者名
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品分類マスタ.作成者名
     *
     * @param 作成者名 the value for public.商品分類マスタ.作成者名
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品分類マスタ.更新日時
     *
     * @return the value of public.商品分類マスタ.更新日時
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品分類マスタ.更新日時
     *
     * @param 更新日時 the value for public.商品分類マスタ.更新日時
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品分類マスタ.更新者名
     *
     * @return the value of public.商品分類マスタ.更新者名
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品分類マスタ.更新者名
     *
     * @param 更新者名 the value for public.商品分類マスタ.更新者名
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }
}
