package com.example.sms.infrastructure.datasource.master.department;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface 部門マスタMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.部門マスタ
     *
     * @mbg.generated Fri Oct 04 15:48:01 JST 2024
     */
    int deleteByPrimaryKey(部門マスタKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.部門マスタ
     *
     * @mbg.generated Fri Oct 04 15:48:01 JST 2024
     */
    int insert(部門マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.部門マスタ
     *
     * @mbg.generated Fri Oct 04 15:48:01 JST 2024
     */
    int insertSelective(部門マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.部門マスタ
     *
     * @mbg.generated Fri Oct 04 15:48:01 JST 2024
     */
    部門マスタ selectByPrimaryKey(部門マスタKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.部門マスタ
     *
     * @mbg.generated Fri Oct 04 15:48:01 JST 2024
     */
    int updateByPrimaryKeySelective(部門マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.部門マスタ
     *
     * @mbg.generated Fri Oct 04 15:48:01 JST 2024
     */
    int updateByPrimaryKey(部門マスタ record);
}
