package com.example.sms.infrastructure.datasource.master.product;

public interface 代替商品Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.代替商品
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    int deleteByPrimaryKey(代替商品Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.代替商品
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    int insert(代替商品 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.代替商品
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    int insertSelective(代替商品 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.代替商品
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    代替商品 selectByPrimaryKey(代替商品Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.代替商品
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    int updateByPrimaryKeySelective(代替商品 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.代替商品
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    int updateByPrimaryKey(代替商品 record);
}
