package com.example.sms.infrastructure.datasource.master.product;

import java.time.LocalDateTime;
import java.util.List;

public class 商品マスタ {
    private List<代替商品> 代替商品;

    public List<代替商品> get代替商品() {
        return 代替商品;
    }

    private List<部品表> 部品表;

    public List<部品表> get部品表() {
        return 部品表;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.商品コード
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private String 商品コード;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.商品正式名
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private String 商品正式名;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.商品略称
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private String 商品略称;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.商品名カナ
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private String 商品名カナ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.商品区分
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private String 商品区分;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.製品型番
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private String 製品型番;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.販売単価
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private Integer 販売単価;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.仕入単価
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private Integer 仕入単価;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.売上原価
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private Integer 売上原価;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.税区分
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private Integer 税区分;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.商品分類コード
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private String 商品分類コード;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.雑区分
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private Integer 雑区分;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.在庫管理対象区分
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private Integer 在庫管理対象区分;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.在庫引当区分
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private Integer 在庫引当区分;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.仕入先コード
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private String 仕入先コード;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.仕入先枝番
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private Integer 仕入先枝番;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.作成日時
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private LocalDateTime 作成日時;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.作成者名
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private String 作成者名;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.更新日時
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private LocalDateTime 更新日時;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.商品マスタ.更新者名
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    private String 更新者名;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.商品コード
     *
     * @return the value of public.商品マスタ.商品コード
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public String get商品コード() {
        return 商品コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.商品コード
     *
     * @param 商品コード the value for public.商品マスタ.商品コード
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set商品コード(String 商品コード) {
        this.商品コード = 商品コード == null ? null : 商品コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.商品正式名
     *
     * @return the value of public.商品マスタ.商品正式名
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public String get商品正式名() {
        return 商品正式名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.商品正式名
     *
     * @param 商品正式名 the value for public.商品マスタ.商品正式名
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set商品正式名(String 商品正式名) {
        this.商品正式名 = 商品正式名 == null ? null : 商品正式名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.商品略称
     *
     * @return the value of public.商品マスタ.商品略称
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public String get商品略称() {
        return 商品略称;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.商品略称
     *
     * @param 商品略称 the value for public.商品マスタ.商品略称
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set商品略称(String 商品略称) {
        this.商品略称 = 商品略称 == null ? null : 商品略称.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.商品名カナ
     *
     * @return the value of public.商品マスタ.商品名カナ
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public String get商品名カナ() {
        return 商品名カナ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.商品名カナ
     *
     * @param 商品名カナ the value for public.商品マスタ.商品名カナ
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set商品名カナ(String 商品名カナ) {
        this.商品名カナ = 商品名カナ == null ? null : 商品名カナ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.商品区分
     *
     * @return the value of public.商品マスタ.商品区分
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public String get商品区分() {
        return 商品区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.商品区分
     *
     * @param 商品区分 the value for public.商品マスタ.商品区分
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set商品区分(String 商品区分) {
        this.商品区分 = 商品区分 == null ? null : 商品区分.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.製品型番
     *
     * @return the value of public.商品マスタ.製品型番
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public String get製品型番() {
        return 製品型番;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.製品型番
     *
     * @param 製品型番 the value for public.商品マスタ.製品型番
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set製品型番(String 製品型番) {
        this.製品型番 = 製品型番 == null ? null : 製品型番.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.販売単価
     *
     * @return the value of public.商品マスタ.販売単価
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public Integer get販売単価() {
        return 販売単価;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.販売単価
     *
     * @param 販売単価 the value for public.商品マスタ.販売単価
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set販売単価(Integer 販売単価) {
        this.販売単価 = 販売単価;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.仕入単価
     *
     * @return the value of public.商品マスタ.仕入単価
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public Integer get仕入単価() {
        return 仕入単価;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.仕入単価
     *
     * @param 仕入単価 the value for public.商品マスタ.仕入単価
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set仕入単価(Integer 仕入単価) {
        this.仕入単価 = 仕入単価;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.売上原価
     *
     * @return the value of public.商品マスタ.売上原価
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public Integer get売上原価() {
        return 売上原価;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.売上原価
     *
     * @param 売上原価 the value for public.商品マスタ.売上原価
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set売上原価(Integer 売上原価) {
        this.売上原価 = 売上原価;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.税区分
     *
     * @return the value of public.商品マスタ.税区分
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public Integer get税区分() {
        return 税区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.税区分
     *
     * @param 税区分 the value for public.商品マスタ.税区分
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set税区分(Integer 税区分) {
        this.税区分 = 税区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.商品分類コード
     *
     * @return the value of public.商品マスタ.商品分類コード
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public String get商品分類コード() {
        return 商品分類コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.商品分類コード
     *
     * @param 商品分類コード the value for public.商品マスタ.商品分類コード
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set商品分類コード(String 商品分類コード) {
        this.商品分類コード = 商品分類コード == null ? null : 商品分類コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.雑区分
     *
     * @return the value of public.商品マスタ.雑区分
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public Integer get雑区分() {
        return 雑区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.雑区分
     *
     * @param 雑区分 the value for public.商品マスタ.雑区分
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set雑区分(Integer 雑区分) {
        this.雑区分 = 雑区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.在庫管理対象区分
     *
     * @return the value of public.商品マスタ.在庫管理対象区分
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public Integer get在庫管理対象区分() {
        return 在庫管理対象区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.在庫管理対象区分
     *
     * @param 在庫管理対象区分 the value for public.商品マスタ.在庫管理対象区分
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set在庫管理対象区分(Integer 在庫管理対象区分) {
        this.在庫管理対象区分 = 在庫管理対象区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.在庫引当区分
     *
     * @return the value of public.商品マスタ.在庫引当区分
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public Integer get在庫引当区分() {
        return 在庫引当区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.在庫引当区分
     *
     * @param 在庫引当区分 the value for public.商品マスタ.在庫引当区分
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set在庫引当区分(Integer 在庫引当区分) {
        this.在庫引当区分 = 在庫引当区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.仕入先コード
     *
     * @return the value of public.商品マスタ.仕入先コード
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public String get仕入先コード() {
        return 仕入先コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.仕入先コード
     *
     * @param 仕入先コード the value for public.商品マスタ.仕入先コード
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set仕入先コード(String 仕入先コード) {
        this.仕入先コード = 仕入先コード == null ? null : 仕入先コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.仕入先枝番
     *
     * @return the value of public.商品マスタ.仕入先枝番
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public Integer get仕入先枝番() {
        return 仕入先枝番;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.仕入先枝番
     *
     * @param 仕入先枝番 the value for public.商品マスタ.仕入先枝番
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set仕入先枝番(Integer 仕入先枝番) {
        this.仕入先枝番 = 仕入先枝番;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.作成日時
     *
     * @return the value of public.商品マスタ.作成日時
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.作成日時
     *
     * @param 作成日時 the value for public.商品マスタ.作成日時
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.作成者名
     *
     * @return the value of public.商品マスタ.作成者名
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.作成者名
     *
     * @param 作成者名 the value for public.商品マスタ.作成者名
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.更新日時
     *
     * @return the value of public.商品マスタ.更新日時
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.更新日時
     *
     * @param 更新日時 the value for public.商品マスタ.更新日時
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.商品マスタ.更新者名
     *
     * @return the value of public.商品マスタ.更新者名
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.商品マスタ.更新者名
     *
     * @param 更新者名 the value for public.商品マスタ.更新者名
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }
}
