package com.example.sms.infrastructure.datasource.master.product;

public interface 部品表Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.部品表
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    int deleteByPrimaryKey(部品表Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.部品表
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    int insert(部品表 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.部品表
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    int insertSelective(部品表 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.部品表
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    部品表 selectByPrimaryKey(部品表Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.部品表
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    int updateByPrimaryKeySelective(部品表 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.部品表
     *
     * @mbg.generated Sat Oct 19 18:42:50 JST 2024
     */
    int updateByPrimaryKey(部品表 record);
}
