package com.example.sms.infrastructure.datasource.system.audit;

import com.example.sms.infrastructure.datasource.system.user.Usr;

import java.time.LocalDateTime;

public class ApplicationExecutionHistoryEntity {
    private Usr user;

    public Usr getUser() {
        return user;
    }

    public void setUser(Usr user) {
        this.user = user;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system.application_execution_history.id
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system.application_execution_history.process_name
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    private String processName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system.application_execution_history.process_code
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    private String processCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system.application_execution_history.process_type
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    private String processType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system.application_execution_history.process_start
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    private LocalDateTime processStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system.application_execution_history.process_end
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    private LocalDateTime processEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system.application_execution_history.process_flag
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    private Integer processFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system.application_execution_history.process_details
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    private String processDetails;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system.application_execution_history.version
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system.application_execution_history.user_id
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system.application_execution_history.id
     *
     * @return the value of system.application_execution_history.id
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system.application_execution_history.id
     *
     * @param id the value for system.application_execution_history.id
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system.application_execution_history.process_name
     *
     * @return the value of system.application_execution_history.process_name
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public String getProcessName() {
        return processName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system.application_execution_history.process_name
     *
     * @param processName the value for system.application_execution_history.process_name
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public void setProcessName(String processName) {
        this.processName = processName == null ? null : processName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system.application_execution_history.process_code
     *
     * @return the value of system.application_execution_history.process_code
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public String getProcessCode() {
        return processCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system.application_execution_history.process_code
     *
     * @param processCode the value for system.application_execution_history.process_code
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public void setProcessCode(String processCode) {
        this.processCode = processCode == null ? null : processCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system.application_execution_history.process_type
     *
     * @return the value of system.application_execution_history.process_type
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public String getProcessType() {
        return processType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system.application_execution_history.process_type
     *
     * @param processType the value for system.application_execution_history.process_type
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public void setProcessType(String processType) {
        this.processType = processType == null ? null : processType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system.application_execution_history.process_start
     *
     * @return the value of system.application_execution_history.process_start
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public LocalDateTime getProcessStart() {
        return processStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system.application_execution_history.process_start
     *
     * @param processStart the value for system.application_execution_history.process_start
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public void setProcessStart(LocalDateTime processStart) {
        this.processStart = processStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system.application_execution_history.process_end
     *
     * @return the value of system.application_execution_history.process_end
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public LocalDateTime getProcessEnd() {
        return processEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system.application_execution_history.process_end
     *
     * @param processEnd the value for system.application_execution_history.process_end
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public void setProcessEnd(LocalDateTime processEnd) {
        this.processEnd = processEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system.application_execution_history.process_flag
     *
     * @return the value of system.application_execution_history.process_flag
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public Integer getProcessFlag() {
        return processFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system.application_execution_history.process_flag
     *
     * @param processFlag the value for system.application_execution_history.process_flag
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public void setProcessFlag(Integer processFlag) {
        this.processFlag = processFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system.application_execution_history.process_details
     *
     * @return the value of system.application_execution_history.process_details
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public String getProcessDetails() {
        return processDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system.application_execution_history.process_details
     *
     * @param processDetails the value for system.application_execution_history.process_details
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public void setProcessDetails(String processDetails) {
        this.processDetails = processDetails == null ? null : processDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system.application_execution_history.version
     *
     * @return the value of system.application_execution_history.version
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system.application_execution_history.version
     *
     * @param version the value for system.application_execution_history.version
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system.application_execution_history.user_id
     *
     * @return the value of system.application_execution_history.user_id
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system.application_execution_history.user_id
     *
     * @param userId the value for system.application_execution_history.user_id
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}