package com.example.sms.infrastructure.datasource.system.audit;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ApplicationExecutionHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system.application_execution_history
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system.application_execution_history
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    int insert(ApplicationExecutionHistoryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system.application_execution_history
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    int insertSelective(ApplicationExecutionHistoryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system.application_execution_history
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    ApplicationExecutionHistoryEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system.application_execution_history
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    int updateByPrimaryKeySelective(ApplicationExecutionHistoryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system.application_execution_history
     *
     * @mbg.generated Sat Dec 07 15:41:15 JST 2024
     */
    int updateByPrimaryKey(ApplicationExecutionHistoryEntity record);

    @Delete("DELETE FROM system.application_execution_history")
    void deleteAll();

    List<ApplicationExecutionHistoryEntity> selectAll();
}