package com.example.sms.infrastructure.datasource.autogen.model;

public class 仕入データ明細Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ明細.仕入行番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private Integer 仕入行番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ明細.仕入番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private String 仕入番号;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ明細.仕入行番号
     *
     * @return the value of public.仕入データ明細.仕入行番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public Integer get仕入行番号() {
        return 仕入行番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ明細.仕入行番号
     *
     * @param 仕入行番号 the value for public.仕入データ明細.仕入行番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set仕入行番号(Integer 仕入行番号) {
        this.仕入行番号 = 仕入行番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ明細.仕入番号
     *
     * @return the value of public.仕入データ明細.仕入番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public String get仕入番号() {
        return 仕入番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ明細.仕入番号
     *
     * @param 仕入番号 the value for public.仕入データ明細.仕入番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set仕入番号(String 仕入番号) {
        this.仕入番号 = 仕入番号 == null ? null : 仕入番号.trim();
    }
}