package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 仕入データ {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ.仕入番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private String 仕入番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ.仕入日
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private LocalDateTime 仕入日;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ.仕入先コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private String 仕入先コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ.仕入先枝番
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private Integer 仕入先枝番;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ.仕入担当者コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private String 仕入担当者コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ.開始日
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private LocalDateTime 開始日;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ.発注番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private String 発注番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ.部門コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private String 部門コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ.仕入金額合計
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private Integer 仕入金額合計;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ.消費税合計
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private Integer 消費税合計;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ.備考
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private String 備考;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ.作成日時
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ.作成者名
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ.更新日時
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ.updater
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private String updater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ.仕入番号
     *
     * @return the value of public.仕入データ.仕入番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public String get仕入番号() {
        return 仕入番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ.仕入番号
     *
     * @param 仕入番号 the value for public.仕入データ.仕入番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set仕入番号(String 仕入番号) {
        this.仕入番号 = 仕入番号 == null ? null : 仕入番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ.仕入日
     *
     * @return the value of public.仕入データ.仕入日
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public LocalDateTime get仕入日() {
        return 仕入日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ.仕入日
     *
     * @param 仕入日 the value for public.仕入データ.仕入日
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set仕入日(LocalDateTime 仕入日) {
        this.仕入日 = 仕入日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ.仕入先コード
     *
     * @return the value of public.仕入データ.仕入先コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public String get仕入先コード() {
        return 仕入先コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ.仕入先コード
     *
     * @param 仕入先コード the value for public.仕入データ.仕入先コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set仕入先コード(String 仕入先コード) {
        this.仕入先コード = 仕入先コード == null ? null : 仕入先コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ.仕入先枝番
     *
     * @return the value of public.仕入データ.仕入先枝番
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public Integer get仕入先枝番() {
        return 仕入先枝番;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ.仕入先枝番
     *
     * @param 仕入先枝番 the value for public.仕入データ.仕入先枝番
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set仕入先枝番(Integer 仕入先枝番) {
        this.仕入先枝番 = 仕入先枝番;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ.仕入担当者コード
     *
     * @return the value of public.仕入データ.仕入担当者コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public String get仕入担当者コード() {
        return 仕入担当者コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ.仕入担当者コード
     *
     * @param 仕入担当者コード the value for public.仕入データ.仕入担当者コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set仕入担当者コード(String 仕入担当者コード) {
        this.仕入担当者コード = 仕入担当者コード == null ? null : 仕入担当者コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ.開始日
     *
     * @return the value of public.仕入データ.開始日
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public LocalDateTime get開始日() {
        return 開始日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ.開始日
     *
     * @param 開始日 the value for public.仕入データ.開始日
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set開始日(LocalDateTime 開始日) {
        this.開始日 = 開始日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ.発注番号
     *
     * @return the value of public.仕入データ.発注番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public String get発注番号() {
        return 発注番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ.発注番号
     *
     * @param 発注番号 the value for public.仕入データ.発注番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set発注番号(String 発注番号) {
        this.発注番号 = 発注番号 == null ? null : 発注番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ.部門コード
     *
     * @return the value of public.仕入データ.部門コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public String get部門コード() {
        return 部門コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ.部門コード
     *
     * @param 部門コード the value for public.仕入データ.部門コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set部門コード(String 部門コード) {
        this.部門コード = 部門コード == null ? null : 部門コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ.仕入金額合計
     *
     * @return the value of public.仕入データ.仕入金額合計
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public Integer get仕入金額合計() {
        return 仕入金額合計;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ.仕入金額合計
     *
     * @param 仕入金額合計 the value for public.仕入データ.仕入金額合計
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set仕入金額合計(Integer 仕入金額合計) {
        this.仕入金額合計 = 仕入金額合計;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ.消費税合計
     *
     * @return the value of public.仕入データ.消費税合計
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public Integer get消費税合計() {
        return 消費税合計;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ.消費税合計
     *
     * @param 消費税合計 the value for public.仕入データ.消費税合計
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set消費税合計(Integer 消費税合計) {
        this.消費税合計 = 消費税合計;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ.備考
     *
     * @return the value of public.仕入データ.備考
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public String get備考() {
        return 備考;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ.備考
     *
     * @param 備考 the value for public.仕入データ.備考
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set備考(String 備考) {
        this.備考 = 備考 == null ? null : 備考.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ.作成日時
     *
     * @return the value of public.仕入データ.作成日時
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ.作成日時
     *
     * @param 作成日時 the value for public.仕入データ.作成日時
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ.作成者名
     *
     * @return the value of public.仕入データ.作成者名
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ.作成者名
     *
     * @param 作成者名 the value for public.仕入データ.作成者名
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ.更新日時
     *
     * @return the value of public.仕入データ.更新日時
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ.更新日時
     *
     * @param 更新日時 the value for public.仕入データ.更新日時
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ.updater
     *
     * @return the value of public.仕入データ.updater
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ.updater
     *
     * @param updater the value for public.仕入データ.updater
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }
}