package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 倉庫マスタ {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.倉庫マスタ.倉庫コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 倉庫コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.倉庫マスタ.倉庫名
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 倉庫名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.倉庫マスタ.倉庫区分
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 倉庫区分;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.倉庫マスタ.郵便番号
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 郵便番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.倉庫マスタ.都道府県
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 都道府県;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.倉庫マスタ.住所１
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 住所１;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.倉庫マスタ.住所２
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 住所２;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.倉庫マスタ.作成日時
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.倉庫マスタ.作成者名
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.倉庫マスタ.更新日時
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.倉庫マスタ.更新者名
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 更新者名;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.倉庫マスタ.倉庫コード
     *
     * @return the value of public.倉庫マスタ.倉庫コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get倉庫コード() {
        return 倉庫コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.倉庫マスタ.倉庫コード
     *
     * @param 倉庫コード the value for public.倉庫マスタ.倉庫コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set倉庫コード(String 倉庫コード) {
        this.倉庫コード = 倉庫コード == null ? null : 倉庫コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.倉庫マスタ.倉庫名
     *
     * @return the value of public.倉庫マスタ.倉庫名
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get倉庫名() {
        return 倉庫名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.倉庫マスタ.倉庫名
     *
     * @param 倉庫名 the value for public.倉庫マスタ.倉庫名
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set倉庫名(String 倉庫名) {
        this.倉庫名 = 倉庫名 == null ? null : 倉庫名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.倉庫マスタ.倉庫区分
     *
     * @return the value of public.倉庫マスタ.倉庫区分
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get倉庫区分() {
        return 倉庫区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.倉庫マスタ.倉庫区分
     *
     * @param 倉庫区分 the value for public.倉庫マスタ.倉庫区分
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set倉庫区分(String 倉庫区分) {
        this.倉庫区分 = 倉庫区分 == null ? null : 倉庫区分.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.倉庫マスタ.郵便番号
     *
     * @return the value of public.倉庫マスタ.郵便番号
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get郵便番号() {
        return 郵便番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.倉庫マスタ.郵便番号
     *
     * @param 郵便番号 the value for public.倉庫マスタ.郵便番号
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set郵便番号(String 郵便番号) {
        this.郵便番号 = 郵便番号 == null ? null : 郵便番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.倉庫マスタ.都道府県
     *
     * @return the value of public.倉庫マスタ.都道府県
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get都道府県() {
        return 都道府県;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.倉庫マスタ.都道府県
     *
     * @param 都道府県 the value for public.倉庫マスタ.都道府県
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set都道府県(String 都道府県) {
        this.都道府県 = 都道府県 == null ? null : 都道府県.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.倉庫マスタ.住所１
     *
     * @return the value of public.倉庫マスタ.住所１
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get住所１() {
        return 住所１;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.倉庫マスタ.住所１
     *
     * @param 住所１ the value for public.倉庫マスタ.住所１
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set住所１(String 住所１) {
        this.住所１ = 住所１ == null ? null : 住所１.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.倉庫マスタ.住所２
     *
     * @return the value of public.倉庫マスタ.住所２
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get住所２() {
        return 住所２;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.倉庫マスタ.住所２
     *
     * @param 住所２ the value for public.倉庫マスタ.住所２
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set住所２(String 住所２) {
        this.住所２ = 住所２ == null ? null : 住所２.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.倉庫マスタ.作成日時
     *
     * @return the value of public.倉庫マスタ.作成日時
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.倉庫マスタ.作成日時
     *
     * @param 作成日時 the value for public.倉庫マスタ.作成日時
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.倉庫マスタ.作成者名
     *
     * @return the value of public.倉庫マスタ.作成者名
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.倉庫マスタ.作成者名
     *
     * @param 作成者名 the value for public.倉庫マスタ.作成者名
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.倉庫マスタ.更新日時
     *
     * @return the value of public.倉庫マスタ.更新日時
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.倉庫マスタ.更新日時
     *
     * @param 更新日時 the value for public.倉庫マスタ.更新日時
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.倉庫マスタ.更新者名
     *
     * @return the value of public.倉庫マスタ.更新者名
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.倉庫マスタ.更新者名
     *
     * @param 更新者名 the value for public.倉庫マスタ.更新者名
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }
}