package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 入金口座マスタ {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金口座マスタ.入金口座コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 入金口座コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金口座マスタ.入金口座名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 入金口座名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金口座マスタ.適用開始日
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private LocalDateTime 適用開始日;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金口座マスタ.適用終了日
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private LocalDateTime 適用終了日;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金口座マスタ.適用開始後入金口座名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 適用開始後入金口座名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金口座マスタ.入金口座区分
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 入金口座区分;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金口座マスタ.入金口座番号
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 入金口座番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金口座マスタ.銀行口座種別
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 銀行口座種別;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金口座マスタ.口座名義人
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 口座名義人;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金口座マスタ.部門コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 部門コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金口座マスタ.部門開始日
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private LocalDateTime 部門開始日;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金口座マスタ.全銀協銀行コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 全銀協銀行コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金口座マスタ.全銀協支店コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 全銀協支店コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金口座マスタ.作成日時
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金口座マスタ.作成者名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金口座マスタ.更新日時
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金口座マスタ.更新者名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 更新者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金口座マスタ.プログラム更新日時
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private LocalDateTime プログラム更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金口座マスタ.更新プログラム名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 更新プログラム名;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金口座マスタ.入金口座コード
     *
     * @return the value of public.入金口座マスタ.入金口座コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get入金口座コード() {
        return 入金口座コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金口座マスタ.入金口座コード
     *
     * @param 入金口座コード the value for public.入金口座マスタ.入金口座コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set入金口座コード(String 入金口座コード) {
        this.入金口座コード = 入金口座コード == null ? null : 入金口座コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金口座マスタ.入金口座名
     *
     * @return the value of public.入金口座マスタ.入金口座名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get入金口座名() {
        return 入金口座名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金口座マスタ.入金口座名
     *
     * @param 入金口座名 the value for public.入金口座マスタ.入金口座名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set入金口座名(String 入金口座名) {
        this.入金口座名 = 入金口座名 == null ? null : 入金口座名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金口座マスタ.適用開始日
     *
     * @return the value of public.入金口座マスタ.適用開始日
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public LocalDateTime get適用開始日() {
        return 適用開始日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金口座マスタ.適用開始日
     *
     * @param 適用開始日 the value for public.入金口座マスタ.適用開始日
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set適用開始日(LocalDateTime 適用開始日) {
        this.適用開始日 = 適用開始日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金口座マスタ.適用終了日
     *
     * @return the value of public.入金口座マスタ.適用終了日
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public LocalDateTime get適用終了日() {
        return 適用終了日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金口座マスタ.適用終了日
     *
     * @param 適用終了日 the value for public.入金口座マスタ.適用終了日
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set適用終了日(LocalDateTime 適用終了日) {
        this.適用終了日 = 適用終了日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金口座マスタ.適用開始後入金口座名
     *
     * @return the value of public.入金口座マスタ.適用開始後入金口座名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get適用開始後入金口座名() {
        return 適用開始後入金口座名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金口座マスタ.適用開始後入金口座名
     *
     * @param 適用開始後入金口座名 the value for public.入金口座マスタ.適用開始後入金口座名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set適用開始後入金口座名(String 適用開始後入金口座名) {
        this.適用開始後入金口座名 = 適用開始後入金口座名 == null ? null : 適用開始後入金口座名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金口座マスタ.入金口座区分
     *
     * @return the value of public.入金口座マスタ.入金口座区分
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get入金口座区分() {
        return 入金口座区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金口座マスタ.入金口座区分
     *
     * @param 入金口座区分 the value for public.入金口座マスタ.入金口座区分
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set入金口座区分(String 入金口座区分) {
        this.入金口座区分 = 入金口座区分 == null ? null : 入金口座区分.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金口座マスタ.入金口座番号
     *
     * @return the value of public.入金口座マスタ.入金口座番号
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get入金口座番号() {
        return 入金口座番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金口座マスタ.入金口座番号
     *
     * @param 入金口座番号 the value for public.入金口座マスタ.入金口座番号
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set入金口座番号(String 入金口座番号) {
        this.入金口座番号 = 入金口座番号 == null ? null : 入金口座番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金口座マスタ.銀行口座種別
     *
     * @return the value of public.入金口座マスタ.銀行口座種別
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get銀行口座種別() {
        return 銀行口座種別;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金口座マスタ.銀行口座種別
     *
     * @param 銀行口座種別 the value for public.入金口座マスタ.銀行口座種別
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set銀行口座種別(String 銀行口座種別) {
        this.銀行口座種別 = 銀行口座種別 == null ? null : 銀行口座種別.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金口座マスタ.口座名義人
     *
     * @return the value of public.入金口座マスタ.口座名義人
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get口座名義人() {
        return 口座名義人;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金口座マスタ.口座名義人
     *
     * @param 口座名義人 the value for public.入金口座マスタ.口座名義人
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set口座名義人(String 口座名義人) {
        this.口座名義人 = 口座名義人 == null ? null : 口座名義人.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金口座マスタ.部門コード
     *
     * @return the value of public.入金口座マスタ.部門コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get部門コード() {
        return 部門コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金口座マスタ.部門コード
     *
     * @param 部門コード the value for public.入金口座マスタ.部門コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set部門コード(String 部門コード) {
        this.部門コード = 部門コード == null ? null : 部門コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金口座マスタ.部門開始日
     *
     * @return the value of public.入金口座マスタ.部門開始日
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public LocalDateTime get部門開始日() {
        return 部門開始日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金口座マスタ.部門開始日
     *
     * @param 部門開始日 the value for public.入金口座マスタ.部門開始日
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set部門開始日(LocalDateTime 部門開始日) {
        this.部門開始日 = 部門開始日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金口座マスタ.全銀協銀行コード
     *
     * @return the value of public.入金口座マスタ.全銀協銀行コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get全銀協銀行コード() {
        return 全銀協銀行コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金口座マスタ.全銀協銀行コード
     *
     * @param 全銀協銀行コード the value for public.入金口座マスタ.全銀協銀行コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set全銀協銀行コード(String 全銀協銀行コード) {
        this.全銀協銀行コード = 全銀協銀行コード == null ? null : 全銀協銀行コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金口座マスタ.全銀協支店コード
     *
     * @return the value of public.入金口座マスタ.全銀協支店コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get全銀協支店コード() {
        return 全銀協支店コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金口座マスタ.全銀協支店コード
     *
     * @param 全銀協支店コード the value for public.入金口座マスタ.全銀協支店コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set全銀協支店コード(String 全銀協支店コード) {
        this.全銀協支店コード = 全銀協支店コード == null ? null : 全銀協支店コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金口座マスタ.作成日時
     *
     * @return the value of public.入金口座マスタ.作成日時
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金口座マスタ.作成日時
     *
     * @param 作成日時 the value for public.入金口座マスタ.作成日時
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金口座マスタ.作成者名
     *
     * @return the value of public.入金口座マスタ.作成者名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金口座マスタ.作成者名
     *
     * @param 作成者名 the value for public.入金口座マスタ.作成者名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金口座マスタ.更新日時
     *
     * @return the value of public.入金口座マスタ.更新日時
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金口座マスタ.更新日時
     *
     * @param 更新日時 the value for public.入金口座マスタ.更新日時
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金口座マスタ.更新者名
     *
     * @return the value of public.入金口座マスタ.更新者名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金口座マスタ.更新者名
     *
     * @param 更新者名 the value for public.入金口座マスタ.更新者名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金口座マスタ.プログラム更新日時
     *
     * @return the value of public.入金口座マスタ.プログラム更新日時
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public LocalDateTime getプログラム更新日時() {
        return プログラム更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金口座マスタ.プログラム更新日時
     *
     * @param プログラム更新日時 the value for public.入金口座マスタ.プログラム更新日時
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void setプログラム更新日時(LocalDateTime プログラム更新日時) {
        this.プログラム更新日時 = プログラム更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金口座マスタ.更新プログラム名
     *
     * @return the value of public.入金口座マスタ.更新プログラム名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get更新プログラム名() {
        return 更新プログラム名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金口座マスタ.更新プログラム名
     *
     * @param 更新プログラム名 the value for public.入金口座マスタ.更新プログラム名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set更新プログラム名(String 更新プログラム名) {
        this.更新プログラム名 = 更新プログラム名 == null ? null : 更新プログラム名.trim();
    }
}