package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 取引先グループマスタ {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先グループマスタ.取引先グループコード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 取引先グループコード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先グループマスタ.取引先グループ名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 取引先グループ名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先グループマスタ.作成日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先グループマスタ.作成者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先グループマスタ.更新日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先グループマスタ.更新者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 更新者名;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先グループマスタ.取引先グループコード
     *
     * @return the value of public.取引先グループマスタ.取引先グループコード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get取引先グループコード() {
        return 取引先グループコード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先グループマスタ.取引先グループコード
     *
     * @param 取引先グループコード the value for public.取引先グループマスタ.取引先グループコード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set取引先グループコード(String 取引先グループコード) {
        this.取引先グループコード = 取引先グループコード == null ? null : 取引先グループコード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先グループマスタ.取引先グループ名
     *
     * @return the value of public.取引先グループマスタ.取引先グループ名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get取引先グループ名() {
        return 取引先グループ名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先グループマスタ.取引先グループ名
     *
     * @param 取引先グループ名 the value for public.取引先グループマスタ.取引先グループ名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set取引先グループ名(String 取引先グループ名) {
        this.取引先グループ名 = 取引先グループ名 == null ? null : 取引先グループ名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先グループマスタ.作成日時
     *
     * @return the value of public.取引先グループマスタ.作成日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先グループマスタ.作成日時
     *
     * @param 作成日時 the value for public.取引先グループマスタ.作成日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先グループマスタ.作成者名
     *
     * @return the value of public.取引先グループマスタ.作成者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先グループマスタ.作成者名
     *
     * @param 作成者名 the value for public.取引先グループマスタ.作成者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先グループマスタ.更新日時
     *
     * @return the value of public.取引先グループマスタ.更新日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先グループマスタ.更新日時
     *
     * @param 更新日時 the value for public.取引先グループマスタ.更新日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先グループマスタ.更新者名
     *
     * @return the value of public.取引先グループマスタ.更新者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先グループマスタ.更新者名
     *
     * @param 更新者名 the value for public.取引先グループマスタ.更新者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }
}