package com.example.sms.infrastructure.datasource.autogen.model;

public class 取引先分類所属マスタKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先分類所属マスタ.取引先分類種別コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 取引先分類種別コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先分類所属マスタ.取引先コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 取引先コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先分類所属マスタ.取引先分類コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 取引先分類コード;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先分類所属マスタ.取引先分類種別コード
     *
     * @return the value of public.取引先分類所属マスタ.取引先分類種別コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get取引先分類種別コード() {
        return 取引先分類種別コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先分類所属マスタ.取引先分類種別コード
     *
     * @param 取引先分類種別コード the value for public.取引先分類所属マスタ.取引先分類種別コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set取引先分類種別コード(String 取引先分類種別コード) {
        this.取引先分類種別コード = 取引先分類種別コード == null ? null : 取引先分類種別コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先分類所属マスタ.取引先コード
     *
     * @return the value of public.取引先分類所属マスタ.取引先コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get取引先コード() {
        return 取引先コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先分類所属マスタ.取引先コード
     *
     * @param 取引先コード the value for public.取引先分類所属マスタ.取引先コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set取引先コード(String 取引先コード) {
        this.取引先コード = 取引先コード == null ? null : 取引先コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先分類所属マスタ.取引先分類コード
     *
     * @return the value of public.取引先分類所属マスタ.取引先分類コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get取引先分類コード() {
        return 取引先分類コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先分類所属マスタ.取引先分類コード
     *
     * @param 取引先分類コード the value for public.取引先分類所属マスタ.取引先分類コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set取引先分類コード(String 取引先分類コード) {
        this.取引先分類コード = 取引先分類コード == null ? null : 取引先分類コード.trim();
    }
}