package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 取引先マスタ {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先マスタ.取引先コード
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    private String 取引先コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先マスタ.取引先名
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    private String 取引先名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先マスタ.取引先名カナ
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    private String 取引先名カナ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先マスタ.仕入先区分
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    private Integer 仕入先区分;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先マスタ.郵便番号
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    private String 郵便番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先マスタ.都道府県
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    private String 都道府県;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先マスタ.住所１
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    private String 住所１;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先マスタ.住所２
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    private String 住所２;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先マスタ.取引禁止フラグ
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    private Integer 取引禁止フラグ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先マスタ.雑区分
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    private Integer 雑区分;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先マスタ.取引先グループコード
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    private String 取引先グループコード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先マスタ.与信限度額
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    private Integer 与信限度額;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先マスタ.与信一時増加枠
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    private Integer 与信一時増加枠;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先マスタ.作成日時
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先マスタ.作成者名
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先マスタ.更新日時
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先マスタ.更新者名
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    private String 更新者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.取引先マスタ.version
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先マスタ.取引先コード
     *
     * @return the value of public.取引先マスタ.取引先コード
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public String get取引先コード() {
        return 取引先コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先マスタ.取引先コード
     *
     * @param 取引先コード the value for public.取引先マスタ.取引先コード
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public void set取引先コード(String 取引先コード) {
        this.取引先コード = 取引先コード == null ? null : 取引先コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先マスタ.取引先名
     *
     * @return the value of public.取引先マスタ.取引先名
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public String get取引先名() {
        return 取引先名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先マスタ.取引先名
     *
     * @param 取引先名 the value for public.取引先マスタ.取引先名
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public void set取引先名(String 取引先名) {
        this.取引先名 = 取引先名 == null ? null : 取引先名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先マスタ.取引先名カナ
     *
     * @return the value of public.取引先マスタ.取引先名カナ
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public String get取引先名カナ() {
        return 取引先名カナ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先マスタ.取引先名カナ
     *
     * @param 取引先名カナ the value for public.取引先マスタ.取引先名カナ
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public void set取引先名カナ(String 取引先名カナ) {
        this.取引先名カナ = 取引先名カナ == null ? null : 取引先名カナ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先マスタ.仕入先区分
     *
     * @return the value of public.取引先マスタ.仕入先区分
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public Integer get仕入先区分() {
        return 仕入先区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先マスタ.仕入先区分
     *
     * @param 仕入先区分 the value for public.取引先マスタ.仕入先区分
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public void set仕入先区分(Integer 仕入先区分) {
        this.仕入先区分 = 仕入先区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先マスタ.郵便番号
     *
     * @return the value of public.取引先マスタ.郵便番号
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public String get郵便番号() {
        return 郵便番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先マスタ.郵便番号
     *
     * @param 郵便番号 the value for public.取引先マスタ.郵便番号
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public void set郵便番号(String 郵便番号) {
        this.郵便番号 = 郵便番号 == null ? null : 郵便番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先マスタ.都道府県
     *
     * @return the value of public.取引先マスタ.都道府県
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public String get都道府県() {
        return 都道府県;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先マスタ.都道府県
     *
     * @param 都道府県 the value for public.取引先マスタ.都道府県
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public void set都道府県(String 都道府県) {
        this.都道府県 = 都道府県 == null ? null : 都道府県.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先マスタ.住所１
     *
     * @return the value of public.取引先マスタ.住所１
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public String get住所１() {
        return 住所１;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先マスタ.住所１
     *
     * @param 住所１ the value for public.取引先マスタ.住所１
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public void set住所１(String 住所１) {
        this.住所１ = 住所１ == null ? null : 住所１.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先マスタ.住所２
     *
     * @return the value of public.取引先マスタ.住所２
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public String get住所２() {
        return 住所２;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先マスタ.住所２
     *
     * @param 住所２ the value for public.取引先マスタ.住所２
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public void set住所２(String 住所２) {
        this.住所２ = 住所２ == null ? null : 住所２.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先マスタ.取引禁止フラグ
     *
     * @return the value of public.取引先マスタ.取引禁止フラグ
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public Integer get取引禁止フラグ() {
        return 取引禁止フラグ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先マスタ.取引禁止フラグ
     *
     * @param 取引禁止フラグ the value for public.取引先マスタ.取引禁止フラグ
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public void set取引禁止フラグ(Integer 取引禁止フラグ) {
        this.取引禁止フラグ = 取引禁止フラグ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先マスタ.雑区分
     *
     * @return the value of public.取引先マスタ.雑区分
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public Integer get雑区分() {
        return 雑区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先マスタ.雑区分
     *
     * @param 雑区分 the value for public.取引先マスタ.雑区分
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public void set雑区分(Integer 雑区分) {
        this.雑区分 = 雑区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先マスタ.取引先グループコード
     *
     * @return the value of public.取引先マスタ.取引先グループコード
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public String get取引先グループコード() {
        return 取引先グループコード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先マスタ.取引先グループコード
     *
     * @param 取引先グループコード the value for public.取引先マスタ.取引先グループコード
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public void set取引先グループコード(String 取引先グループコード) {
        this.取引先グループコード = 取引先グループコード == null ? null : 取引先グループコード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先マスタ.与信限度額
     *
     * @return the value of public.取引先マスタ.与信限度額
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public Integer get与信限度額() {
        return 与信限度額;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先マスタ.与信限度額
     *
     * @param 与信限度額 the value for public.取引先マスタ.与信限度額
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public void set与信限度額(Integer 与信限度額) {
        this.与信限度額 = 与信限度額;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先マスタ.与信一時増加枠
     *
     * @return the value of public.取引先マスタ.与信一時増加枠
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public Integer get与信一時増加枠() {
        return 与信一時増加枠;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先マスタ.与信一時増加枠
     *
     * @param 与信一時増加枠 the value for public.取引先マスタ.与信一時増加枠
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public void set与信一時増加枠(Integer 与信一時増加枠) {
        this.与信一時増加枠 = 与信一時増加枠;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先マスタ.作成日時
     *
     * @return the value of public.取引先マスタ.作成日時
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先マスタ.作成日時
     *
     * @param 作成日時 the value for public.取引先マスタ.作成日時
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先マスタ.作成者名
     *
     * @return the value of public.取引先マスタ.作成者名
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先マスタ.作成者名
     *
     * @param 作成者名 the value for public.取引先マスタ.作成者名
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先マスタ.更新日時
     *
     * @return the value of public.取引先マスタ.更新日時
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先マスタ.更新日時
     *
     * @param 更新日時 the value for public.取引先マスタ.更新日時
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先マスタ.更新者名
     *
     * @return the value of public.取引先マスタ.更新者名
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先マスタ.更新者名
     *
     * @param 更新者名 the value for public.取引先マスタ.更新者名
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.取引先マスタ.version
     *
     * @return the value of public.取引先マスタ.version
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.取引先マスタ.version
     *
     * @param version the value for public.取引先マスタ.version
     *
     * @mbg.generated Sat Jan 11 12:54:37 JST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}