package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 受注データ明細 extends 受注データ明細Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.受注データ明細.商品コード
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    private String 商品コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.受注データ明細.商品名
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    private String 商品名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.受注データ明細.販売単価
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    private Integer 販売単価;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.受注データ明細.受注数量
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    private Integer 受注数量;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.受注データ明細.消費税率
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    private Integer 消費税率;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.受注データ明細.引当数量
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    private Integer 引当数量;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.受注データ明細.出荷指示数量
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    private Integer 出荷指示数量;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.受注データ明細.出荷済数量
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    private Integer 出荷済数量;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.受注データ明細.完了フラグ
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    private Integer 完了フラグ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.受注データ明細.値引金額
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    private Integer 値引金額;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.受注データ明細.納期
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    private LocalDateTime 納期;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.受注データ明細.作成日時
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.受注データ明細.作成者名
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.受注データ明細.更新日時
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.受注データ明細.更新者名
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    private String 更新者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.受注データ明細.出荷日
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    private LocalDateTime 出荷日;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.受注データ明細.商品コード
     *
     * @return the value of public.受注データ明細.商品コード
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public String get商品コード() {
        return 商品コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.受注データ明細.商品コード
     *
     * @param 商品コード the value for public.受注データ明細.商品コード
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public void set商品コード(String 商品コード) {
        this.商品コード = 商品コード == null ? null : 商品コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.受注データ明細.商品名
     *
     * @return the value of public.受注データ明細.商品名
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public String get商品名() {
        return 商品名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.受注データ明細.商品名
     *
     * @param 商品名 the value for public.受注データ明細.商品名
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public void set商品名(String 商品名) {
        this.商品名 = 商品名 == null ? null : 商品名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.受注データ明細.販売単価
     *
     * @return the value of public.受注データ明細.販売単価
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public Integer get販売単価() {
        return 販売単価;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.受注データ明細.販売単価
     *
     * @param 販売単価 the value for public.受注データ明細.販売単価
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public void set販売単価(Integer 販売単価) {
        this.販売単価 = 販売単価;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.受注データ明細.受注数量
     *
     * @return the value of public.受注データ明細.受注数量
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public Integer get受注数量() {
        return 受注数量;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.受注データ明細.受注数量
     *
     * @param 受注数量 the value for public.受注データ明細.受注数量
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public void set受注数量(Integer 受注数量) {
        this.受注数量 = 受注数量;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.受注データ明細.消費税率
     *
     * @return the value of public.受注データ明細.消費税率
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public Integer get消費税率() {
        return 消費税率;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.受注データ明細.消費税率
     *
     * @param 消費税率 the value for public.受注データ明細.消費税率
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public void set消費税率(Integer 消費税率) {
        this.消費税率 = 消費税率;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.受注データ明細.引当数量
     *
     * @return the value of public.受注データ明細.引当数量
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public Integer get引当数量() {
        return 引当数量;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.受注データ明細.引当数量
     *
     * @param 引当数量 the value for public.受注データ明細.引当数量
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public void set引当数量(Integer 引当数量) {
        this.引当数量 = 引当数量;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.受注データ明細.出荷指示数量
     *
     * @return the value of public.受注データ明細.出荷指示数量
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public Integer get出荷指示数量() {
        return 出荷指示数量;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.受注データ明細.出荷指示数量
     *
     * @param 出荷指示数量 the value for public.受注データ明細.出荷指示数量
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public void set出荷指示数量(Integer 出荷指示数量) {
        this.出荷指示数量 = 出荷指示数量;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.受注データ明細.出荷済数量
     *
     * @return the value of public.受注データ明細.出荷済数量
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public Integer get出荷済数量() {
        return 出荷済数量;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.受注データ明細.出荷済数量
     *
     * @param 出荷済数量 the value for public.受注データ明細.出荷済数量
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public void set出荷済数量(Integer 出荷済数量) {
        this.出荷済数量 = 出荷済数量;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.受注データ明細.完了フラグ
     *
     * @return the value of public.受注データ明細.完了フラグ
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public Integer get完了フラグ() {
        return 完了フラグ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.受注データ明細.完了フラグ
     *
     * @param 完了フラグ the value for public.受注データ明細.完了フラグ
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public void set完了フラグ(Integer 完了フラグ) {
        this.完了フラグ = 完了フラグ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.受注データ明細.値引金額
     *
     * @return the value of public.受注データ明細.値引金額
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public Integer get値引金額() {
        return 値引金額;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.受注データ明細.値引金額
     *
     * @param 値引金額 the value for public.受注データ明細.値引金額
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public void set値引金額(Integer 値引金額) {
        this.値引金額 = 値引金額;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.受注データ明細.納期
     *
     * @return the value of public.受注データ明細.納期
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public LocalDateTime get納期() {
        return 納期;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.受注データ明細.納期
     *
     * @param 納期 the value for public.受注データ明細.納期
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public void set納期(LocalDateTime 納期) {
        this.納期 = 納期;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.受注データ明細.作成日時
     *
     * @return the value of public.受注データ明細.作成日時
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.受注データ明細.作成日時
     *
     * @param 作成日時 the value for public.受注データ明細.作成日時
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.受注データ明細.作成者名
     *
     * @return the value of public.受注データ明細.作成者名
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.受注データ明細.作成者名
     *
     * @param 作成者名 the value for public.受注データ明細.作成者名
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.受注データ明細.更新日時
     *
     * @return the value of public.受注データ明細.更新日時
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.受注データ明細.更新日時
     *
     * @param 更新日時 the value for public.受注データ明細.更新日時
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.受注データ明細.更新者名
     *
     * @return the value of public.受注データ明細.更新者名
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.受注データ明細.更新者名
     *
     * @param 更新者名 the value for public.受注データ明細.更新者名
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.受注データ明細.出荷日
     *
     * @return the value of public.受注データ明細.出荷日
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public LocalDateTime get出荷日() {
        return 出荷日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.受注データ明細.出荷日
     *
     * @param 出荷日 the value for public.受注データ明細.出荷日
     *
     * @mbg.generated Wed May 28 16:55:33 JST 2025
     */
    public void set出荷日(LocalDateTime 出荷日) {
        this.出荷日 = 出荷日;
    }
}