package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 売上データ {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.売上番号
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private String 売上番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.受注番号
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private String 受注番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.売上日
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private LocalDateTime 売上日;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.売上区分
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private Integer 売上区分;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.部門コード
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private String 部門コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.部門開始日
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private LocalDateTime 部門開始日;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.取引先コード
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private String 取引先コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.社員コード
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private String 社員コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.売上金額合計
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private Integer 売上金額合計;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.消費税合計
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private Integer 消費税合計;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.備考
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private String 備考;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.赤黒伝票番号
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private Integer 赤黒伝票番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.元伝票番号
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private String 元伝票番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.作成日時
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.作成者名
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.更新日時
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.更新者名
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private String 更新者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.version
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.顧客コード
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private String 顧客コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.売上データ.顧客枝番
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    private Integer 顧客枝番;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.売上番号
     *
     * @return the value of public.売上データ.売上番号
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public String get売上番号() {
        return 売上番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.売上番号
     *
     * @param 売上番号 the value for public.売上データ.売上番号
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void set売上番号(String 売上番号) {
        this.売上番号 = 売上番号 == null ? null : 売上番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.受注番号
     *
     * @return the value of public.売上データ.受注番号
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public String get受注番号() {
        return 受注番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.受注番号
     *
     * @param 受注番号 the value for public.売上データ.受注番号
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void set受注番号(String 受注番号) {
        this.受注番号 = 受注番号 == null ? null : 受注番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.売上日
     *
     * @return the value of public.売上データ.売上日
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public LocalDateTime get売上日() {
        return 売上日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.売上日
     *
     * @param 売上日 the value for public.売上データ.売上日
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void set売上日(LocalDateTime 売上日) {
        this.売上日 = 売上日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.売上区分
     *
     * @return the value of public.売上データ.売上区分
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public Integer get売上区分() {
        return 売上区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.売上区分
     *
     * @param 売上区分 the value for public.売上データ.売上区分
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void set売上区分(Integer 売上区分) {
        this.売上区分 = 売上区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.部門コード
     *
     * @return the value of public.売上データ.部門コード
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public String get部門コード() {
        return 部門コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.部門コード
     *
     * @param 部門コード the value for public.売上データ.部門コード
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void set部門コード(String 部門コード) {
        this.部門コード = 部門コード == null ? null : 部門コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.部門開始日
     *
     * @return the value of public.売上データ.部門開始日
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public LocalDateTime get部門開始日() {
        return 部門開始日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.部門開始日
     *
     * @param 部門開始日 the value for public.売上データ.部門開始日
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void set部門開始日(LocalDateTime 部門開始日) {
        this.部門開始日 = 部門開始日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.取引先コード
     *
     * @return the value of public.売上データ.取引先コード
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public String get取引先コード() {
        return 取引先コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.取引先コード
     *
     * @param 取引先コード the value for public.売上データ.取引先コード
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void set取引先コード(String 取引先コード) {
        this.取引先コード = 取引先コード == null ? null : 取引先コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.社員コード
     *
     * @return the value of public.売上データ.社員コード
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public String get社員コード() {
        return 社員コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.社員コード
     *
     * @param 社員コード the value for public.売上データ.社員コード
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void set社員コード(String 社員コード) {
        this.社員コード = 社員コード == null ? null : 社員コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.売上金額合計
     *
     * @return the value of public.売上データ.売上金額合計
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public Integer get売上金額合計() {
        return 売上金額合計;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.売上金額合計
     *
     * @param 売上金額合計 the value for public.売上データ.売上金額合計
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void set売上金額合計(Integer 売上金額合計) {
        this.売上金額合計 = 売上金額合計;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.消費税合計
     *
     * @return the value of public.売上データ.消費税合計
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public Integer get消費税合計() {
        return 消費税合計;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.消費税合計
     *
     * @param 消費税合計 the value for public.売上データ.消費税合計
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void set消費税合計(Integer 消費税合計) {
        this.消費税合計 = 消費税合計;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.備考
     *
     * @return the value of public.売上データ.備考
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public String get備考() {
        return 備考;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.備考
     *
     * @param 備考 the value for public.売上データ.備考
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void set備考(String 備考) {
        this.備考 = 備考 == null ? null : 備考.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.赤黒伝票番号
     *
     * @return the value of public.売上データ.赤黒伝票番号
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public Integer get赤黒伝票番号() {
        return 赤黒伝票番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.赤黒伝票番号
     *
     * @param 赤黒伝票番号 the value for public.売上データ.赤黒伝票番号
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void set赤黒伝票番号(Integer 赤黒伝票番号) {
        this.赤黒伝票番号 = 赤黒伝票番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.元伝票番号
     *
     * @return the value of public.売上データ.元伝票番号
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public String get元伝票番号() {
        return 元伝票番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.元伝票番号
     *
     * @param 元伝票番号 the value for public.売上データ.元伝票番号
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void set元伝票番号(String 元伝票番号) {
        this.元伝票番号 = 元伝票番号 == null ? null : 元伝票番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.作成日時
     *
     * @return the value of public.売上データ.作成日時
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.作成日時
     *
     * @param 作成日時 the value for public.売上データ.作成日時
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.作成者名
     *
     * @return the value of public.売上データ.作成者名
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.作成者名
     *
     * @param 作成者名 the value for public.売上データ.作成者名
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.更新日時
     *
     * @return the value of public.売上データ.更新日時
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.更新日時
     *
     * @param 更新日時 the value for public.売上データ.更新日時
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.更新者名
     *
     * @return the value of public.売上データ.更新者名
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.更新者名
     *
     * @param 更新者名 the value for public.売上データ.更新者名
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.version
     *
     * @return the value of public.売上データ.version
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.version
     *
     * @param version the value for public.売上データ.version
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.顧客コード
     *
     * @return the value of public.売上データ.顧客コード
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public String get顧客コード() {
        return 顧客コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.顧客コード
     *
     * @param 顧客コード the value for public.売上データ.顧客コード
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void set顧客コード(String 顧客コード) {
        this.顧客コード = 顧客コード == null ? null : 顧客コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.売上データ.顧客枝番
     *
     * @return the value of public.売上データ.顧客枝番
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public Integer get顧客枝番() {
        return 顧客枝番;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.売上データ.顧客枝番
     *
     * @param 顧客枝番 the value for public.売上データ.顧客枝番
     *
     * @mbg.generated Wed May 14 15:53:35 JST 2025
     */
    public void set顧客枝番(Integer 顧客枝番) {
        this.顧客枝番 = 顧客枝番;
    }
}