package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 支払データ {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.支払データ.支払番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private String 支払番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.支払データ.支払日
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private Integer 支払日;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.支払データ.部門コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private String 部門コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.支払データ.部門開始日
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private LocalDateTime 部門開始日;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.支払データ.仕入先コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private String 仕入先コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.支払データ.仕入先枝番
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private Integer 仕入先枝番;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.支払データ.支払方法区分
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private Integer 支払方法区分;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.支払データ.支払金額
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private Integer 支払金額;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.支払データ.消費税合計
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private Integer 消費税合計;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.支払データ.支払完了フラグ
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private Integer 支払完了フラグ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.支払データ.作成日時
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.支払データ.作成者名
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.支払データ.更新日時
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.支払データ.更新者名
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private String 更新者名;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.支払データ.支払番号
     *
     * @return the value of public.支払データ.支払番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public String get支払番号() {
        return 支払番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.支払データ.支払番号
     *
     * @param 支払番号 the value for public.支払データ.支払番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set支払番号(String 支払番号) {
        this.支払番号 = 支払番号 == null ? null : 支払番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.支払データ.支払日
     *
     * @return the value of public.支払データ.支払日
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public Integer get支払日() {
        return 支払日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.支払データ.支払日
     *
     * @param 支払日 the value for public.支払データ.支払日
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set支払日(Integer 支払日) {
        this.支払日 = 支払日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.支払データ.部門コード
     *
     * @return the value of public.支払データ.部門コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public String get部門コード() {
        return 部門コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.支払データ.部門コード
     *
     * @param 部門コード the value for public.支払データ.部門コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set部門コード(String 部門コード) {
        this.部門コード = 部門コード == null ? null : 部門コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.支払データ.部門開始日
     *
     * @return the value of public.支払データ.部門開始日
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public LocalDateTime get部門開始日() {
        return 部門開始日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.支払データ.部門開始日
     *
     * @param 部門開始日 the value for public.支払データ.部門開始日
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set部門開始日(LocalDateTime 部門開始日) {
        this.部門開始日 = 部門開始日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.支払データ.仕入先コード
     *
     * @return the value of public.支払データ.仕入先コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public String get仕入先コード() {
        return 仕入先コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.支払データ.仕入先コード
     *
     * @param 仕入先コード the value for public.支払データ.仕入先コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set仕入先コード(String 仕入先コード) {
        this.仕入先コード = 仕入先コード == null ? null : 仕入先コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.支払データ.仕入先枝番
     *
     * @return the value of public.支払データ.仕入先枝番
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public Integer get仕入先枝番() {
        return 仕入先枝番;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.支払データ.仕入先枝番
     *
     * @param 仕入先枝番 the value for public.支払データ.仕入先枝番
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set仕入先枝番(Integer 仕入先枝番) {
        this.仕入先枝番 = 仕入先枝番;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.支払データ.支払方法区分
     *
     * @return the value of public.支払データ.支払方法区分
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public Integer get支払方法区分() {
        return 支払方法区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.支払データ.支払方法区分
     *
     * @param 支払方法区分 the value for public.支払データ.支払方法区分
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set支払方法区分(Integer 支払方法区分) {
        this.支払方法区分 = 支払方法区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.支払データ.支払金額
     *
     * @return the value of public.支払データ.支払金額
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public Integer get支払金額() {
        return 支払金額;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.支払データ.支払金額
     *
     * @param 支払金額 the value for public.支払データ.支払金額
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set支払金額(Integer 支払金額) {
        this.支払金額 = 支払金額;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.支払データ.消費税合計
     *
     * @return the value of public.支払データ.消費税合計
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public Integer get消費税合計() {
        return 消費税合計;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.支払データ.消費税合計
     *
     * @param 消費税合計 the value for public.支払データ.消費税合計
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set消費税合計(Integer 消費税合計) {
        this.消費税合計 = 消費税合計;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.支払データ.支払完了フラグ
     *
     * @return the value of public.支払データ.支払完了フラグ
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public Integer get支払完了フラグ() {
        return 支払完了フラグ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.支払データ.支払完了フラグ
     *
     * @param 支払完了フラグ the value for public.支払データ.支払完了フラグ
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set支払完了フラグ(Integer 支払完了フラグ) {
        this.支払完了フラグ = 支払完了フラグ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.支払データ.作成日時
     *
     * @return the value of public.支払データ.作成日時
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.支払データ.作成日時
     *
     * @param 作成日時 the value for public.支払データ.作成日時
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.支払データ.作成者名
     *
     * @return the value of public.支払データ.作成者名
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.支払データ.作成者名
     *
     * @param 作成者名 the value for public.支払データ.作成者名
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.支払データ.更新日時
     *
     * @return the value of public.支払データ.更新日時
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.支払データ.更新日時
     *
     * @param 更新日時 the value for public.支払データ.更新日時
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.支払データ.更新者名
     *
     * @return the value of public.支払データ.更新者名
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.支払データ.更新者名
     *
     * @param 更新者名 the value for public.支払データ.更新者名
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }
}