package com.example.sms.infrastructure.datasource.autogen.model;

public class 棚番マスタKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.棚番マスタ.倉庫コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 倉庫コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.棚番マスタ.棚番コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 棚番コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.棚番マスタ.商品コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 商品コード;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.棚番マスタ.倉庫コード
     *
     * @return the value of public.棚番マスタ.倉庫コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get倉庫コード() {
        return 倉庫コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.棚番マスタ.倉庫コード
     *
     * @param 倉庫コード the value for public.棚番マスタ.倉庫コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set倉庫コード(String 倉庫コード) {
        this.倉庫コード = 倉庫コード == null ? null : 倉庫コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.棚番マスタ.棚番コード
     *
     * @return the value of public.棚番マスタ.棚番コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get棚番コード() {
        return 棚番コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.棚番マスタ.棚番コード
     *
     * @param 棚番コード the value for public.棚番マスタ.棚番コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set棚番コード(String 棚番コード) {
        this.棚番コード = 棚番コード == null ? null : 棚番コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.棚番マスタ.商品コード
     *
     * @return the value of public.棚番マスタ.商品コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get商品コード() {
        return 商品コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.棚番マスタ.商品コード
     *
     * @param 商品コード the value for public.棚番マスタ.商品コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set商品コード(String 商品コード) {
        this.商品コード = 商品コード == null ? null : 商品コード.trim();
    }
}