package com.example.sms.infrastructure.datasource.autogen.model;

public class 発注データ明細Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ明細.発注行番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private Integer 発注行番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ明細.発注番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private String 発注番号;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ明細.発注行番号
     *
     * @return the value of public.発注データ明細.発注行番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public Integer get発注行番号() {
        return 発注行番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ明細.発注行番号
     *
     * @param 発注行番号 the value for public.発注データ明細.発注行番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set発注行番号(Integer 発注行番号) {
        this.発注行番号 = 発注行番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ明細.発注番号
     *
     * @return the value of public.発注データ明細.発注番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public String get発注番号() {
        return 発注番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ明細.発注番号
     *
     * @param 発注番号 the value for public.発注データ明細.発注番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set発注番号(String 発注番号) {
        this.発注番号 = 発注番号 == null ? null : 発注番号.trim();
    }
}