package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 発注データ {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ.発注番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private String 発注番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ.発注日
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private LocalDateTime 発注日;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ.受注番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private String 受注番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ.仕入先コード
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private String 仕入先コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ.仕入先枝番
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private Integer 仕入先枝番;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ.発注担当者コード
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private String 発注担当者コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ.指定納期
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private LocalDateTime 指定納期;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ.倉庫コード
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private String 倉庫コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ.発注金額合計
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private Integer 発注金額合計;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ.消費税合計
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private Integer 消費税合計;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ.備考
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private String 備考;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ.作成日時
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ.作成者名
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ.更新日時
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ.更新者名
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private String 更新者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ.version
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ.発注番号
     *
     * @return the value of public.発注データ.発注番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public String get発注番号() {
        return 発注番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ.発注番号
     *
     * @param 発注番号 the value for public.発注データ.発注番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set発注番号(String 発注番号) {
        this.発注番号 = 発注番号 == null ? null : 発注番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ.発注日
     *
     * @return the value of public.発注データ.発注日
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public LocalDateTime get発注日() {
        return 発注日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ.発注日
     *
     * @param 発注日 the value for public.発注データ.発注日
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set発注日(LocalDateTime 発注日) {
        this.発注日 = 発注日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ.受注番号
     *
     * @return the value of public.発注データ.受注番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public String get受注番号() {
        return 受注番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ.受注番号
     *
     * @param 受注番号 the value for public.発注データ.受注番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set受注番号(String 受注番号) {
        this.受注番号 = 受注番号 == null ? null : 受注番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ.仕入先コード
     *
     * @return the value of public.発注データ.仕入先コード
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public String get仕入先コード() {
        return 仕入先コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ.仕入先コード
     *
     * @param 仕入先コード the value for public.発注データ.仕入先コード
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set仕入先コード(String 仕入先コード) {
        this.仕入先コード = 仕入先コード == null ? null : 仕入先コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ.仕入先枝番
     *
     * @return the value of public.発注データ.仕入先枝番
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public Integer get仕入先枝番() {
        return 仕入先枝番;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ.仕入先枝番
     *
     * @param 仕入先枝番 the value for public.発注データ.仕入先枝番
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set仕入先枝番(Integer 仕入先枝番) {
        this.仕入先枝番 = 仕入先枝番;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ.発注担当者コード
     *
     * @return the value of public.発注データ.発注担当者コード
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public String get発注担当者コード() {
        return 発注担当者コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ.発注担当者コード
     *
     * @param 発注担当者コード the value for public.発注データ.発注担当者コード
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set発注担当者コード(String 発注担当者コード) {
        this.発注担当者コード = 発注担当者コード == null ? null : 発注担当者コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ.指定納期
     *
     * @return the value of public.発注データ.指定納期
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public LocalDateTime get指定納期() {
        return 指定納期;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ.指定納期
     *
     * @param 指定納期 the value for public.発注データ.指定納期
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set指定納期(LocalDateTime 指定納期) {
        this.指定納期 = 指定納期;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ.倉庫コード
     *
     * @return the value of public.発注データ.倉庫コード
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public String get倉庫コード() {
        return 倉庫コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ.倉庫コード
     *
     * @param 倉庫コード the value for public.発注データ.倉庫コード
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set倉庫コード(String 倉庫コード) {
        this.倉庫コード = 倉庫コード == null ? null : 倉庫コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ.発注金額合計
     *
     * @return the value of public.発注データ.発注金額合計
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public Integer get発注金額合計() {
        return 発注金額合計;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ.発注金額合計
     *
     * @param 発注金額合計 the value for public.発注データ.発注金額合計
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set発注金額合計(Integer 発注金額合計) {
        this.発注金額合計 = 発注金額合計;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ.消費税合計
     *
     * @return the value of public.発注データ.消費税合計
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public Integer get消費税合計() {
        return 消費税合計;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ.消費税合計
     *
     * @param 消費税合計 the value for public.発注データ.消費税合計
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set消費税合計(Integer 消費税合計) {
        this.消費税合計 = 消費税合計;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ.備考
     *
     * @return the value of public.発注データ.備考
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public String get備考() {
        return 備考;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ.備考
     *
     * @param 備考 the value for public.発注データ.備考
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set備考(String 備考) {
        this.備考 = 備考 == null ? null : 備考.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ.作成日時
     *
     * @return the value of public.発注データ.作成日時
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ.作成日時
     *
     * @param 作成日時 the value for public.発注データ.作成日時
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ.作成者名
     *
     * @return the value of public.発注データ.作成者名
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ.作成者名
     *
     * @param 作成者名 the value for public.発注データ.作成者名
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ.更新日時
     *
     * @return the value of public.発注データ.更新日時
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ.更新日時
     *
     * @param 更新日時 the value for public.発注データ.更新日時
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ.更新者名
     *
     * @return the value of public.発注データ.更新者名
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ.更新者名
     *
     * @param 更新者名 the value for public.発注データ.更新者名
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ.version
     *
     * @return the value of public.発注データ.version
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ.version
     *
     * @param version the value for public.発注データ.version
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}