package com.example.sms.infrastructure.datasource.autogen.model;

public class 自動採番マスタ extends 自動採番マスタKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.自動採番マスタ.最終伝票番号
     *
     * @mbg.generated Mon Mar 31 13:42:42 JST 2025
     */
    private Integer 最終伝票番号;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.自動採番マスタ.最終伝票番号
     *
     * @return the value of public.自動採番マスタ.最終伝票番号
     *
     * @mbg.generated Mon Mar 31 13:42:42 JST 2025
     */
    public Integer get最終伝票番号() {
        return 最終伝票番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.自動採番マスタ.最終伝票番号
     *
     * @param 最終伝票番号 the value for public.自動採番マスタ.最終伝票番号
     *
     * @mbg.generated Mon Mar 31 13:42:42 JST 2025
     */
    public void set最終伝票番号(Integer 最終伝票番号) {
        this.最終伝票番号 = 最終伝票番号;
    }
}