package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 部品表 extends 部品表Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.部品表.部品数量
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    private Integer 部品数量;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.部品表.作成日時
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.部品表.作成者名
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.部品表.更新日時
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.部品表.更新者名
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    private String 更新者名;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.部品表.部品数量
     *
     * @return the value of public.部品表.部品数量
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    public Integer get部品数量() {
        return 部品数量;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.部品表.部品数量
     *
     * @param 部品数量 the value for public.部品表.部品数量
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    public void set部品数量(Integer 部品数量) {
        this.部品数量 = 部品数量;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.部品表.作成日時
     *
     * @return the value of public.部品表.作成日時
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.部品表.作成日時
     *
     * @param 作成日時 the value for public.部品表.作成日時
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.部品表.作成者名
     *
     * @return the value of public.部品表.作成者名
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.部品表.作成者名
     *
     * @param 作成者名 the value for public.部品表.作成者名
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.部品表.更新日時
     *
     * @return the value of public.部品表.更新日時
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.部品表.更新日時
     *
     * @param 更新日時 the value for public.部品表.更新日時
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.部品表.更新者名
     *
     * @return the value of public.部品表.更新者名
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.部品表.更新者名
     *
     * @param 更新者名 the value for public.部品表.更新者名
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }
}