package com.example.sms.infrastructure.datasource.autogen.model;

public class 部品表Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.部品表.商品コード
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    private String 商品コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.部品表.部品コード
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    private String 部品コード;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.部品表.商品コード
     *
     * @return the value of public.部品表.商品コード
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    public String get商品コード() {
        return 商品コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.部品表.商品コード
     *
     * @param 商品コード the value for public.部品表.商品コード
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    public void set商品コード(String 商品コード) {
        this.商品コード = 商品コード == null ? null : 商品コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.部品表.部品コード
     *
     * @return the value of public.部品表.部品コード
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    public String get部品コード() {
        return 部品コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.部品表.部品コード
     *
     * @param 部品コード the value for public.部品表.部品コード
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    public void set部品コード(String 部品コード) {
        this.部品コード = 部品コード == null ? null : 部品コード.trim();
    }
}