package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 部門マスタ extends 部門マスタKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.部門マスタ.終了日
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    private LocalDateTime 終了日;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.部門マスタ.部門名
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    private String 部門名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.部門マスタ.組織階層
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    private Integer 組織階層;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.部門マスタ.部門パス
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    private String 部門パス;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.部門マスタ.最下層区分
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    private Integer 最下層区分;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.部門マスタ.伝票入力可否
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    private Integer 伝票入力可否;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.部門マスタ.作成日時
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.部門マスタ.作成者名
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.部門マスタ.更新日時
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.部門マスタ.更新者名
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    private String 更新者名;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.部門マスタ.終了日
     *
     * @return the value of public.部門マスタ.終了日
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public LocalDateTime get終了日() {
        return 終了日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.部門マスタ.終了日
     *
     * @param 終了日 the value for public.部門マスタ.終了日
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public void set終了日(LocalDateTime 終了日) {
        this.終了日 = 終了日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.部門マスタ.部門名
     *
     * @return the value of public.部門マスタ.部門名
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public String get部門名() {
        return 部門名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.部門マスタ.部門名
     *
     * @param 部門名 the value for public.部門マスタ.部門名
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public void set部門名(String 部門名) {
        this.部門名 = 部門名 == null ? null : 部門名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.部門マスタ.組織階層
     *
     * @return the value of public.部門マスタ.組織階層
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public Integer get組織階層() {
        return 組織階層;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.部門マスタ.組織階層
     *
     * @param 組織階層 the value for public.部門マスタ.組織階層
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public void set組織階層(Integer 組織階層) {
        this.組織階層 = 組織階層;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.部門マスタ.部門パス
     *
     * @return the value of public.部門マスタ.部門パス
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public String get部門パス() {
        return 部門パス;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.部門マスタ.部門パス
     *
     * @param 部門パス the value for public.部門マスタ.部門パス
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public void set部門パス(String 部門パス) {
        this.部門パス = 部門パス == null ? null : 部門パス.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.部門マスタ.最下層区分
     *
     * @return the value of public.部門マスタ.最下層区分
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public Integer get最下層区分() {
        return 最下層区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.部門マスタ.最下層区分
     *
     * @param 最下層区分 the value for public.部門マスタ.最下層区分
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public void set最下層区分(Integer 最下層区分) {
        this.最下層区分 = 最下層区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.部門マスタ.伝票入力可否
     *
     * @return the value of public.部門マスタ.伝票入力可否
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public Integer get伝票入力可否() {
        return 伝票入力可否;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.部門マスタ.伝票入力可否
     *
     * @param 伝票入力可否 the value for public.部門マスタ.伝票入力可否
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public void set伝票入力可否(Integer 伝票入力可否) {
        this.伝票入力可否 = 伝票入力可否;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.部門マスタ.作成日時
     *
     * @return the value of public.部門マスタ.作成日時
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.部門マスタ.作成日時
     *
     * @param 作成日時 the value for public.部門マスタ.作成日時
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.部門マスタ.作成者名
     *
     * @return the value of public.部門マスタ.作成者名
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.部門マスタ.作成者名
     *
     * @param 作成者名 the value for public.部門マスタ.作成者名
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.部門マスタ.更新日時
     *
     * @return the value of public.部門マスタ.更新日時
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.部門マスタ.更新日時
     *
     * @param 更新日時 the value for public.部門マスタ.更新日時
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.部門マスタ.更新者名
     *
     * @return the value of public.部門マスタ.更新者名
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.部門マスタ.更新者名
     *
     * @param 更新者名 the value for public.部門マスタ.更新者名
     *
     * @mbg.generated Fri Dec 27 09:59:07 JST 2024
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }
}