package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 顧客マスタ extends 顧客マスタKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客区分
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private Integer 顧客区分;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.請求先コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 請求先コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.請求先枝番
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private Integer 請求先枝番;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.回収先コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 回収先コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.回収先枝番
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private Integer 回収先枝番;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 顧客名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客名カナ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 顧客名カナ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.自社担当者コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 自社担当者コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客担当者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 顧客担当者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客部門名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 顧客部門名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客郵便番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 顧客郵便番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客都道府県
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 顧客都道府県;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客住所１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 顧客住所１;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客住所２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 顧客住所２;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客電話番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 顧客電話番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客ＦＡＸ番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 顧客ｆａｘ番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客メールアドレス
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 顧客メールアドレス;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客請求区分
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private Integer 顧客請求区分;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客締日１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private Integer 顧客締日１;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客支払月１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private Integer 顧客支払月１;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客支払日１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private Integer 顧客支払日１;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客支払方法１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private Integer 顧客支払方法１;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客締日２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private Integer 顧客締日２;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客支払月２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private Integer 顧客支払月２;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客支払日２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private Integer 顧客支払日２;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.顧客支払方法２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private Integer 顧客支払方法２;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.作成日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.作成者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.更新日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客マスタ.更新者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 更新者名;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客区分
     *
     * @return the value of public.顧客マスタ.顧客区分
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public Integer get顧客区分() {
        return 顧客区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客区分
     *
     * @param 顧客区分 the value for public.顧客マスタ.顧客区分
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客区分(Integer 顧客区分) {
        this.顧客区分 = 顧客区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.請求先コード
     *
     * @return the value of public.顧客マスタ.請求先コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get請求先コード() {
        return 請求先コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.請求先コード
     *
     * @param 請求先コード the value for public.顧客マスタ.請求先コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set請求先コード(String 請求先コード) {
        this.請求先コード = 請求先コード == null ? null : 請求先コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.請求先枝番
     *
     * @return the value of public.顧客マスタ.請求先枝番
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public Integer get請求先枝番() {
        return 請求先枝番;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.請求先枝番
     *
     * @param 請求先枝番 the value for public.顧客マスタ.請求先枝番
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set請求先枝番(Integer 請求先枝番) {
        this.請求先枝番 = 請求先枝番;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.回収先コード
     *
     * @return the value of public.顧客マスタ.回収先コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get回収先コード() {
        return 回収先コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.回収先コード
     *
     * @param 回収先コード the value for public.顧客マスタ.回収先コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set回収先コード(String 回収先コード) {
        this.回収先コード = 回収先コード == null ? null : 回収先コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.回収先枝番
     *
     * @return the value of public.顧客マスタ.回収先枝番
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public Integer get回収先枝番() {
        return 回収先枝番;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.回収先枝番
     *
     * @param 回収先枝番 the value for public.顧客マスタ.回収先枝番
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set回収先枝番(Integer 回収先枝番) {
        this.回収先枝番 = 回収先枝番;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客名
     *
     * @return the value of public.顧客マスタ.顧客名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get顧客名() {
        return 顧客名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客名
     *
     * @param 顧客名 the value for public.顧客マスタ.顧客名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客名(String 顧客名) {
        this.顧客名 = 顧客名 == null ? null : 顧客名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客名カナ
     *
     * @return the value of public.顧客マスタ.顧客名カナ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get顧客名カナ() {
        return 顧客名カナ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客名カナ
     *
     * @param 顧客名カナ the value for public.顧客マスタ.顧客名カナ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客名カナ(String 顧客名カナ) {
        this.顧客名カナ = 顧客名カナ == null ? null : 顧客名カナ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.自社担当者コード
     *
     * @return the value of public.顧客マスタ.自社担当者コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get自社担当者コード() {
        return 自社担当者コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.自社担当者コード
     *
     * @param 自社担当者コード the value for public.顧客マスタ.自社担当者コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set自社担当者コード(String 自社担当者コード) {
        this.自社担当者コード = 自社担当者コード == null ? null : 自社担当者コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客担当者名
     *
     * @return the value of public.顧客マスタ.顧客担当者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get顧客担当者名() {
        return 顧客担当者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客担当者名
     *
     * @param 顧客担当者名 the value for public.顧客マスタ.顧客担当者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客担当者名(String 顧客担当者名) {
        this.顧客担当者名 = 顧客担当者名 == null ? null : 顧客担当者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客部門名
     *
     * @return the value of public.顧客マスタ.顧客部門名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get顧客部門名() {
        return 顧客部門名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客部門名
     *
     * @param 顧客部門名 the value for public.顧客マスタ.顧客部門名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客部門名(String 顧客部門名) {
        this.顧客部門名 = 顧客部門名 == null ? null : 顧客部門名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客郵便番号
     *
     * @return the value of public.顧客マスタ.顧客郵便番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get顧客郵便番号() {
        return 顧客郵便番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客郵便番号
     *
     * @param 顧客郵便番号 the value for public.顧客マスタ.顧客郵便番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客郵便番号(String 顧客郵便番号) {
        this.顧客郵便番号 = 顧客郵便番号 == null ? null : 顧客郵便番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客都道府県
     *
     * @return the value of public.顧客マスタ.顧客都道府県
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get顧客都道府県() {
        return 顧客都道府県;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客都道府県
     *
     * @param 顧客都道府県 the value for public.顧客マスタ.顧客都道府県
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客都道府県(String 顧客都道府県) {
        this.顧客都道府県 = 顧客都道府県 == null ? null : 顧客都道府県.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客住所１
     *
     * @return the value of public.顧客マスタ.顧客住所１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get顧客住所１() {
        return 顧客住所１;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客住所１
     *
     * @param 顧客住所１ the value for public.顧客マスタ.顧客住所１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客住所１(String 顧客住所１) {
        this.顧客住所１ = 顧客住所１ == null ? null : 顧客住所１.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客住所２
     *
     * @return the value of public.顧客マスタ.顧客住所２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get顧客住所２() {
        return 顧客住所２;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客住所２
     *
     * @param 顧客住所２ the value for public.顧客マスタ.顧客住所２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客住所２(String 顧客住所２) {
        this.顧客住所２ = 顧客住所２ == null ? null : 顧客住所２.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客電話番号
     *
     * @return the value of public.顧客マスタ.顧客電話番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get顧客電話番号() {
        return 顧客電話番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客電話番号
     *
     * @param 顧客電話番号 the value for public.顧客マスタ.顧客電話番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客電話番号(String 顧客電話番号) {
        this.顧客電話番号 = 顧客電話番号 == null ? null : 顧客電話番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客ＦＡＸ番号
     *
     * @return the value of public.顧客マスタ.顧客ＦＡＸ番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get顧客ｆａｘ番号() {
        return 顧客ｆａｘ番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客ＦＡＸ番号
     *
     * @param 顧客ｆａｘ番号 the value for public.顧客マスタ.顧客ＦＡＸ番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客ｆａｘ番号(String 顧客ｆａｘ番号) {
        this.顧客ｆａｘ番号 = 顧客ｆａｘ番号 == null ? null : 顧客ｆａｘ番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客メールアドレス
     *
     * @return the value of public.顧客マスタ.顧客メールアドレス
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get顧客メールアドレス() {
        return 顧客メールアドレス;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客メールアドレス
     *
     * @param 顧客メールアドレス the value for public.顧客マスタ.顧客メールアドレス
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客メールアドレス(String 顧客メールアドレス) {
        this.顧客メールアドレス = 顧客メールアドレス == null ? null : 顧客メールアドレス.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客請求区分
     *
     * @return the value of public.顧客マスタ.顧客請求区分
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public Integer get顧客請求区分() {
        return 顧客請求区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客請求区分
     *
     * @param 顧客請求区分 the value for public.顧客マスタ.顧客請求区分
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客請求区分(Integer 顧客請求区分) {
        this.顧客請求区分 = 顧客請求区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客締日１
     *
     * @return the value of public.顧客マスタ.顧客締日１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public Integer get顧客締日１() {
        return 顧客締日１;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客締日１
     *
     * @param 顧客締日１ the value for public.顧客マスタ.顧客締日１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客締日１(Integer 顧客締日１) {
        this.顧客締日１ = 顧客締日１;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客支払月１
     *
     * @return the value of public.顧客マスタ.顧客支払月１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public Integer get顧客支払月１() {
        return 顧客支払月１;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客支払月１
     *
     * @param 顧客支払月１ the value for public.顧客マスタ.顧客支払月１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客支払月１(Integer 顧客支払月１) {
        this.顧客支払月１ = 顧客支払月１;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客支払日１
     *
     * @return the value of public.顧客マスタ.顧客支払日１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public Integer get顧客支払日１() {
        return 顧客支払日１;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客支払日１
     *
     * @param 顧客支払日１ the value for public.顧客マスタ.顧客支払日１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客支払日１(Integer 顧客支払日１) {
        this.顧客支払日１ = 顧客支払日１;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客支払方法１
     *
     * @return the value of public.顧客マスタ.顧客支払方法１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public Integer get顧客支払方法１() {
        return 顧客支払方法１;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客支払方法１
     *
     * @param 顧客支払方法１ the value for public.顧客マスタ.顧客支払方法１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客支払方法１(Integer 顧客支払方法１) {
        this.顧客支払方法１ = 顧客支払方法１;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客締日２
     *
     * @return the value of public.顧客マスタ.顧客締日２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public Integer get顧客締日２() {
        return 顧客締日２;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客締日２
     *
     * @param 顧客締日２ the value for public.顧客マスタ.顧客締日２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客締日２(Integer 顧客締日２) {
        this.顧客締日２ = 顧客締日２;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客支払月２
     *
     * @return the value of public.顧客マスタ.顧客支払月２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public Integer get顧客支払月２() {
        return 顧客支払月２;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客支払月２
     *
     * @param 顧客支払月２ the value for public.顧客マスタ.顧客支払月２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客支払月２(Integer 顧客支払月２) {
        this.顧客支払月２ = 顧客支払月２;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客支払日２
     *
     * @return the value of public.顧客マスタ.顧客支払日２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public Integer get顧客支払日２() {
        return 顧客支払日２;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客支払日２
     *
     * @param 顧客支払日２ the value for public.顧客マスタ.顧客支払日２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客支払日２(Integer 顧客支払日２) {
        this.顧客支払日２ = 顧客支払日２;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.顧客支払方法２
     *
     * @return the value of public.顧客マスタ.顧客支払方法２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public Integer get顧客支払方法２() {
        return 顧客支払方法２;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.顧客支払方法２
     *
     * @param 顧客支払方法２ the value for public.顧客マスタ.顧客支払方法２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set顧客支払方法２(Integer 顧客支払方法２) {
        this.顧客支払方法２ = 顧客支払方法２;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.作成日時
     *
     * @return the value of public.顧客マスタ.作成日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.作成日時
     *
     * @param 作成日時 the value for public.顧客マスタ.作成日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.作成者名
     *
     * @return the value of public.顧客マスタ.作成者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.作成者名
     *
     * @param 作成者名 the value for public.顧客マスタ.作成者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.更新日時
     *
     * @return the value of public.顧客マスタ.更新日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.更新日時
     *
     * @param 更新日時 the value for public.顧客マスタ.更新日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客マスタ.更新者名
     *
     * @return the value of public.顧客マスタ.更新者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客マスタ.更新者名
     *
     * @param 更新者名 the value for public.顧客マスタ.更新者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }
}