package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 顧客別販売単価 extends 顧客別販売単価Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客別販売単価.販売単価
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    private Integer 販売単価;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客別販売単価.作成日時
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客別販売単価.作成者名
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客別販売単価.更新日時
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.顧客別販売単価.更新者名
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    private String 更新者名;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客別販売単価.販売単価
     *
     * @return the value of public.顧客別販売単価.販売単価
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    public Integer get販売単価() {
        return 販売単価;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客別販売単価.販売単価
     *
     * @param 販売単価 the value for public.顧客別販売単価.販売単価
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    public void set販売単価(Integer 販売単価) {
        this.販売単価 = 販売単価;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客別販売単価.作成日時
     *
     * @return the value of public.顧客別販売単価.作成日時
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客別販売単価.作成日時
     *
     * @param 作成日時 the value for public.顧客別販売単価.作成日時
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客別販売単価.作成者名
     *
     * @return the value of public.顧客別販売単価.作成者名
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客別販売単価.作成者名
     *
     * @param 作成者名 the value for public.顧客別販売単価.作成者名
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客別販売単価.更新日時
     *
     * @return the value of public.顧客別販売単価.更新日時
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客別販売単価.更新日時
     *
     * @param 更新日時 the value for public.顧客別販売単価.更新日時
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.顧客別販売単価.更新者名
     *
     * @return the value of public.顧客別販売単価.更新者名
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.顧客別販売単価.更新者名
     *
     * @param 更新者名 the value for public.顧客別販売単価.更新者名
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }
}