package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.仕入データ;

public interface 仕入データMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.仕入データ
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    int deleteByPrimaryKey(String 仕入番号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.仕入データ
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    int insert(仕入データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.仕入データ
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    int insertSelective(仕入データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.仕入データ
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    仕入データ selectByPrimaryKey(String 仕入番号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.仕入データ
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    int updateByPrimaryKeySelective(仕入データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.仕入データ
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    int updateByPrimaryKey(仕入データ record);
}