package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.仕入データ明細;
import com.example.sms.infrastructure.datasource.autogen.model.仕入データ明細Key;

public interface 仕入データ明細Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.仕入データ明細
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    int deleteByPrimaryKey(仕入データ明細Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.仕入データ明細
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    int insert(仕入データ明細 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.仕入データ明細
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    int insertSelective(仕入データ明細 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.仕入データ明細
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    仕入データ明細 selectByPrimaryKey(仕入データ明細Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.仕入データ明細
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    int updateByPrimaryKeySelective(仕入データ明細 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.仕入データ明細
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    int updateByPrimaryKey(仕入データ明細 record);
}