package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.出荷先マスタ;
import com.example.sms.infrastructure.datasource.autogen.model.出荷先マスタKey;

public interface 出荷先マスタMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.出荷先マスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int deleteByPrimaryKey(出荷先マスタKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.出荷先マスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int insert(出荷先マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.出荷先マスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int insertSelective(出荷先マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.出荷先マスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    出荷先マスタ selectByPrimaryKey(出荷先マスタKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.出荷先マスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int updateByPrimaryKeySelective(出荷先マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.出荷先マスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int updateByPrimaryKey(出荷先マスタ record);
}