package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.地域マスタ;

public interface 地域マスタMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.地域マスタ
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    int deleteByPrimaryKey(String 地域コード);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.地域マスタ
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    int insert(地域マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.地域マスタ
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    int insertSelective(地域マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.地域マスタ
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    地域マスタ selectByPrimaryKey(String 地域コード);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.地域マスタ
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    int updateByPrimaryKeySelective(地域マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.地域マスタ
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    int updateByPrimaryKey(地域マスタ record);
}