package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.発注データ明細;
import com.example.sms.infrastructure.datasource.autogen.model.発注データ明細Key;

public interface 発注データ明細Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.発注データ明細
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    int deleteByPrimaryKey(発注データ明細Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.発注データ明細
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    int insert(発注データ明細 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.発注データ明細
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    int insertSelective(発注データ明細 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.発注データ明細
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    発注データ明細 selectByPrimaryKey(発注データ明細Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.発注データ明細
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    int updateByPrimaryKeySelective(発注データ明細 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.発注データ明細
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    int updateByPrimaryKey(発注データ明細 record);
}