package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.発注データ;

public interface 発注データMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.発注データ
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    int deleteByPrimaryKey(String 発注番号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.発注データ
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    int insert(発注データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.発注データ
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    int insertSelective(発注データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.発注データ
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    発注データ selectByPrimaryKey(String 発注番号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.発注データ
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    int updateByPrimaryKeySelective(発注データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.発注データ
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    int updateByPrimaryKey(発注データ record);
}