package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.請求データ明細;
import com.example.sms.infrastructure.datasource.autogen.model.請求データ明細Key;

public interface 請求データ明細Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.請求データ明細
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    int deleteByPrimaryKey(請求データ明細Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.請求データ明細
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    int insert(請求データ明細 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.請求データ明細
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    int insertSelective(請求データ明細 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.請求データ明細
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    請求データ明細 selectByPrimaryKey(請求データ明細Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.請求データ明細
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    int updateByPrimaryKeySelective(請求データ明細 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.請求データ明細
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    int updateByPrimaryKey(請求データ明細 record);
}