package com.example.sms.infrastructure.datasource.system.user;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface UsrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system.usr
     *
     * @mbg.generated Fri Oct 04 15:48:01 JST 2024
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system.usr
     *
     * @mbg.generated Fri Oct 04 15:48:01 JST 2024
     */
    int insert(Usr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system.usr
     *
     * @mbg.generated Fri Oct 04 15:48:01 JST 2024
     */
    int insertSelective(Usr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system.usr
     *
     * @mbg.generated Fri Oct 04 15:48:01 JST 2024
     */
    Usr selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system.usr
     *
     * @mbg.generated Fri Oct 04 15:48:01 JST 2024
     */
    int updateByPrimaryKeySelective(Usr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system.usr
     *
     * @mbg.generated Fri Oct 04 15:48:01 JST 2024
     */
    int updateByPrimaryKey(Usr record);

    List<Usr> selectAll();

    @Select("DELETE FROM system.usr")
    void deleteAll();
}
