package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.代替商品;
import com.example.sms.infrastructure.datasource.autogen.model.代替商品Key;

public interface 代替商品Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.代替商品
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    int deleteByPrimaryKey(代替商品Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.代替商品
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    int insert(代替商品 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.代替商品
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    int insertSelective(代替商品 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.代替商品
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    代替商品 selectByPrimaryKey(代替商品Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.代替商品
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    int updateByPrimaryKeySelective(代替商品 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.代替商品
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    int updateByPrimaryKey(代替商品 record);
}