package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.倉庫部門マスタ;
import com.example.sms.infrastructure.datasource.autogen.model.倉庫部門マスタKey;

public interface 倉庫部門マスタMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.倉庫部門マスタ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int deleteByPrimaryKey(倉庫部門マスタKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.倉庫部門マスタ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int insert(倉庫部門マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.倉庫部門マスタ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int insertSelective(倉庫部門マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.倉庫部門マスタ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    倉庫部門マスタ selectByPrimaryKey(倉庫部門マスタKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.倉庫部門マスタ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int updateByPrimaryKeySelective(倉庫部門マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.倉庫部門マスタ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int updateByPrimaryKey(倉庫部門マスタ record);
}