package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.倉庫マスタ;

public interface 倉庫マスタMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.倉庫マスタ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int deleteByPrimaryKey(String 倉庫コード);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.倉庫マスタ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int insert(倉庫マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.倉庫マスタ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int insertSelective(倉庫マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.倉庫マスタ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    倉庫マスタ selectByPrimaryKey(String 倉庫コード);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.倉庫マスタ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int updateByPrimaryKeySelective(倉庫マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.倉庫マスタ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int updateByPrimaryKey(倉庫マスタ record);
}