package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.入金データ;

public interface 入金データMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.入金データ
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    int deleteByPrimaryKey(String 入金番号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.入金データ
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    int insert(入金データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.入金データ
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    int insertSelective(入金データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.入金データ
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    入金データ selectByPrimaryKey(String 入金番号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.入金データ
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    int updateByPrimaryKeySelective(入金データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.入金データ
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    int updateByPrimaryKey(入金データ record);
}