package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.入金口座マスタ;

public interface 入金口座マスタMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.入金口座マスタ
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    int deleteByPrimaryKey(String 入金口座コード);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.入金口座マスタ
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    int insert(入金口座マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.入金口座マスタ
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    int insertSelective(入金口座マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.入金口座マスタ
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    入金口座マスタ selectByPrimaryKey(String 入金口座コード);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.入金口座マスタ
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    int updateByPrimaryKeySelective(入金口座マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.入金口座マスタ
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    int updateByPrimaryKey(入金口座マスタ record);
}