package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.取引先分類所属マスタ;
import com.example.sms.infrastructure.datasource.autogen.model.取引先分類所属マスタKey;

public interface 取引先分類所属マスタMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.取引先分類所属マスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int deleteByPrimaryKey(取引先分類所属マスタKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.取引先分類所属マスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int insert(取引先分類所属マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.取引先分類所属マスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int insertSelective(取引先分類所属マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.取引先分類所属マスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    取引先分類所属マスタ selectByPrimaryKey(取引先分類所属マスタKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.取引先分類所属マスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int updateByPrimaryKeySelective(取引先分類所属マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.取引先分類所属マスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int updateByPrimaryKey(取引先分類所属マスタ record);
}