package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.取引先グループマスタ;

public interface 取引先グループマスタMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.取引先グループマスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int deleteByPrimaryKey(String 取引先グループコード);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.取引先グループマスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int insert(取引先グループマスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.取引先グループマスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int insertSelective(取引先グループマスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.取引先グループマスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    取引先グループマスタ selectByPrimaryKey(String 取引先グループコード);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.取引先グループマスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int updateByPrimaryKeySelective(取引先グループマスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.取引先グループマスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int updateByPrimaryKey(取引先グループマスタ record);
}