package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.受注データ明細;
import com.example.sms.infrastructure.datasource.autogen.model.受注データ明細Key;

public interface 受注データ明細Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.受注データ明細
     *
     * @mbg.generated Mon Feb 17 17:55:57 JST 2025
     */
    int deleteByPrimaryKey(受注データ明細Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.受注データ明細
     *
     * @mbg.generated Mon Feb 17 17:55:57 JST 2025
     */
    int insert(受注データ明細 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.受注データ明細
     *
     * @mbg.generated Mon Feb 17 17:55:57 JST 2025
     */
    int insertSelective(受注データ明細 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.受注データ明細
     *
     * @mbg.generated Mon Feb 17 17:55:57 JST 2025
     */
    受注データ明細 selectByPrimaryKey(受注データ明細Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.受注データ明細
     *
     * @mbg.generated Mon Feb 17 17:55:57 JST 2025
     */
    int updateByPrimaryKeySelective(受注データ明細 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.受注データ明細
     *
     * @mbg.generated Mon Feb 17 17:55:57 JST 2025
     */
    int updateByPrimaryKey(受注データ明細 record);
}