package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.商品マスタ;

public interface 商品マスタMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.商品マスタ
     *
     * @mbg.generated Thu Dec 19 19:45:38 JST 2024
     */
    int deleteByPrimaryKey(String 商品コード);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.商品マスタ
     *
     * @mbg.generated Thu Dec 19 19:45:38 JST 2024
     */
    int insert(商品マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.商品マスタ
     *
     * @mbg.generated Thu Dec 19 19:45:38 JST 2024
     */
    int insertSelective(商品マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.商品マスタ
     *
     * @mbg.generated Thu Dec 19 19:45:38 JST 2024
     */
    商品マスタ selectByPrimaryKey(String 商品コード);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.商品マスタ
     *
     * @mbg.generated Thu Dec 19 19:45:38 JST 2024
     */
    int updateByPrimaryKeySelective(商品マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.商品マスタ
     *
     * @mbg.generated Thu Dec 19 19:45:38 JST 2024
     */
    int updateByPrimaryKey(商品マスタ record);
}