package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.商品分類マスタ;

public interface 商品分類マスタMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.商品分類マスタ
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    int deleteByPrimaryKey(String 商品分類コード);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.商品分類マスタ
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    int insert(商品分類マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.商品分類マスタ
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    int insertSelective(商品分類マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.商品分類マスタ
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    商品分類マスタ selectByPrimaryKey(String 商品分類コード);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.商品分類マスタ
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    int updateByPrimaryKeySelective(商品分類マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.商品分類マスタ
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    int updateByPrimaryKey(商品分類マスタ record);
}