package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.在庫データ;
import com.example.sms.infrastructure.datasource.autogen.model.在庫データKey;

public interface 在庫データMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.在庫データ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int deleteByPrimaryKey(在庫データKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.在庫データ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int insert(在庫データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.在庫データ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int insertSelective(在庫データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.在庫データ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    在庫データ selectByPrimaryKey(在庫データKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.在庫データ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int updateByPrimaryKeySelective(在庫データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.在庫データ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int updateByPrimaryKey(在庫データ record);
}