package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.売上データ;

public interface 売上データMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.売上データ
     *
     * @mbg.generated Mon Mar 31 13:42:42 JST 2025
     */
    int deleteByPrimaryKey(String 売上番号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.売上データ
     *
     * @mbg.generated Mon Mar 31 13:42:42 JST 2025
     */
    int insert(売上データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.売上データ
     *
     * @mbg.generated Mon Mar 31 13:42:42 JST 2025
     */
    int insertSelective(売上データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.売上データ
     *
     * @mbg.generated Mon Mar 31 13:42:42 JST 2025
     */
    売上データ selectByPrimaryKey(String 売上番号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.売上データ
     *
     * @mbg.generated Mon Mar 31 13:42:42 JST 2025
     */
    int updateByPrimaryKeySelective(売上データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.売上データ
     *
     * @mbg.generated Mon Mar 31 13:42:42 JST 2025
     */
    int updateByPrimaryKey(売上データ record);
}