package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.売上データ明細;
import com.example.sms.infrastructure.datasource.autogen.model.売上データ明細Key;

public interface 売上データ明細Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.売上データ明細
     *
     * @mbg.generated Thu Apr 17 16:07:54 JST 2025
     */
    int deleteByPrimaryKey(売上データ明細Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.売上データ明細
     *
     * @mbg.generated Thu Apr 17 16:07:54 JST 2025
     */
    int insert(売上データ明細 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.売上データ明細
     *
     * @mbg.generated Thu Apr 17 16:07:54 JST 2025
     */
    int insertSelective(売上データ明細 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.売上データ明細
     *
     * @mbg.generated Thu Apr 17 16:07:54 JST 2025
     */
    売上データ明細 selectByPrimaryKey(売上データ明細Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.売上データ明細
     *
     * @mbg.generated Thu Apr 17 16:07:54 JST 2025
     */
    int updateByPrimaryKeySelective(売上データ明細 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.売上データ明細
     *
     * @mbg.generated Thu Apr 17 16:07:54 JST 2025
     */
    int updateByPrimaryKey(売上データ明細 record);
}