package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.支払データ;

public interface 支払データMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.支払データ
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    int deleteByPrimaryKey(String 支払番号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.支払データ
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    int insert(支払データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.支払データ
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    int insertSelective(支払データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.支払データ
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    支払データ selectByPrimaryKey(String 支払番号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.支払データ
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    int updateByPrimaryKeySelective(支払データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.支払データ
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    int updateByPrimaryKey(支払データ record);
}