package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.棚番マスタ;
import com.example.sms.infrastructure.datasource.autogen.model.棚番マスタKey;

public interface 棚番マスタMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.棚番マスタ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int deleteByPrimaryKey(棚番マスタKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.棚番マスタ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int insert(棚番マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.棚番マスタ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int insertSelective(棚番マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.棚番マスタ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    棚番マスタ selectByPrimaryKey(棚番マスタKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.棚番マスタ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int updateByPrimaryKeySelective(棚番マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.棚番マスタ
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    int updateByPrimaryKey(棚番マスタ record);
}