package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.社員マスタ;

public interface 社員マスタMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.社員マスタ
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    int deleteByPrimaryKey(String 社員コード);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.社員マスタ
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    int insert(社員マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.社員マスタ
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    int insertSelective(社員マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.社員マスタ
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    社員マスタ selectByPrimaryKey(String 社員コード);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.社員マスタ
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    int updateByPrimaryKeySelective(社員マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.社員マスタ
     *
     * @mbg.generated Thu Dec 19 20:11:17 JST 2024
     */
    int updateByPrimaryKey(社員マスタ record);
}