package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.請求データ;

public interface 請求データMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.請求データ
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    int deleteByPrimaryKey(String 請求番号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.請求データ
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    int insert(請求データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.請求データ
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    int insertSelective(請求データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.請求データ
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    請求データ selectByPrimaryKey(String 請求番号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.請求データ
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    int updateByPrimaryKeySelective(請求データ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.請求データ
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    int updateByPrimaryKey(請求データ record);
}