package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.顧客別販売単価;
import com.example.sms.infrastructure.datasource.autogen.model.顧客別販売単価Key;

public interface 顧客別販売単価Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.顧客別販売単価
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    int deleteByPrimaryKey(顧客別販売単価Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.顧客別販売単価
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    int insert(顧客別販売単価 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.顧客別販売単価
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    int insertSelective(顧客別販売単価 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.顧客別販売単価
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    顧客別販売単価 selectByPrimaryKey(顧客別販売単価Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.顧客別販売単価
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    int updateByPrimaryKeySelective(顧客別販売単価 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.顧客別販売単価
     *
     * @mbg.generated Thu Dec 19 13:39:38 JST 2024
     */
    int updateByPrimaryKey(顧客別販売単価 record);
}