package com.example.sms.infrastructure.datasource.autogen.mapper;

import com.example.sms.infrastructure.datasource.autogen.model.顧客マスタ;
import com.example.sms.infrastructure.datasource.autogen.model.顧客マスタKey;

public interface 顧客マスタMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.顧客マスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int deleteByPrimaryKey(顧客マスタKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.顧客マスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int insert(顧客マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.顧客マスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int insertSelective(顧客マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.顧客マスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    顧客マスタ selectByPrimaryKey(顧客マスタKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.顧客マスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int updateByPrimaryKeySelective(顧客マスタ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.顧客マスタ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    int updateByPrimaryKey(顧客マスタ record);
}