name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "case-study-sales-api" #Must be unique in Heroku
          heroku_email: "kakimomokuri@gmail.com"
          appdir: "api" # <- This will point to the api folder in your project
