package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 仕入データ明細 extends 仕入データ明細Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ明細.仕入行表示番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private Integer 仕入行表示番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ明細.発注行番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private Integer 発注行番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ明細.商品コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private String 商品コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ明細.倉庫コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private String 倉庫コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ明細.商品名
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private String 商品名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ明細.仕入単価
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private Integer 仕入単価;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ明細.仕入数量
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private Integer 仕入数量;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ明細.作成日時
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ明細.作成者名
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ明細.更新日時
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入データ明細.更新者名
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    private String 更新者名;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ明細.仕入行表示番号
     *
     * @return the value of public.仕入データ明細.仕入行表示番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public Integer get仕入行表示番号() {
        return 仕入行表示番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ明細.仕入行表示番号
     *
     * @param 仕入行表示番号 the value for public.仕入データ明細.仕入行表示番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set仕入行表示番号(Integer 仕入行表示番号) {
        this.仕入行表示番号 = 仕入行表示番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ明細.発注行番号
     *
     * @return the value of public.仕入データ明細.発注行番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public Integer get発注行番号() {
        return 発注行番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ明細.発注行番号
     *
     * @param 発注行番号 the value for public.仕入データ明細.発注行番号
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set発注行番号(Integer 発注行番号) {
        this.発注行番号 = 発注行番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ明細.商品コード
     *
     * @return the value of public.仕入データ明細.商品コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public String get商品コード() {
        return 商品コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ明細.商品コード
     *
     * @param 商品コード the value for public.仕入データ明細.商品コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set商品コード(String 商品コード) {
        this.商品コード = 商品コード == null ? null : 商品コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ明細.倉庫コード
     *
     * @return the value of public.仕入データ明細.倉庫コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public String get倉庫コード() {
        return 倉庫コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ明細.倉庫コード
     *
     * @param 倉庫コード the value for public.仕入データ明細.倉庫コード
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set倉庫コード(String 倉庫コード) {
        this.倉庫コード = 倉庫コード == null ? null : 倉庫コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ明細.商品名
     *
     * @return the value of public.仕入データ明細.商品名
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public String get商品名() {
        return 商品名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ明細.商品名
     *
     * @param 商品名 the value for public.仕入データ明細.商品名
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set商品名(String 商品名) {
        this.商品名 = 商品名 == null ? null : 商品名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ明細.仕入単価
     *
     * @return the value of public.仕入データ明細.仕入単価
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public Integer get仕入単価() {
        return 仕入単価;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ明細.仕入単価
     *
     * @param 仕入単価 the value for public.仕入データ明細.仕入単価
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set仕入単価(Integer 仕入単価) {
        this.仕入単価 = 仕入単価;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ明細.仕入数量
     *
     * @return the value of public.仕入データ明細.仕入数量
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public Integer get仕入数量() {
        return 仕入数量;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ明細.仕入数量
     *
     * @param 仕入数量 the value for public.仕入データ明細.仕入数量
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set仕入数量(Integer 仕入数量) {
        this.仕入数量 = 仕入数量;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ明細.作成日時
     *
     * @return the value of public.仕入データ明細.作成日時
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ明細.作成日時
     *
     * @param 作成日時 the value for public.仕入データ明細.作成日時
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ明細.作成者名
     *
     * @return the value of public.仕入データ明細.作成者名
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ明細.作成者名
     *
     * @param 作成者名 the value for public.仕入データ明細.作成者名
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ明細.更新日時
     *
     * @return the value of public.仕入データ明細.更新日時
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ明細.更新日時
     *
     * @param 更新日時 the value for public.仕入データ明細.更新日時
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入データ明細.更新者名
     *
     * @return the value of public.仕入データ明細.更新者名
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入データ明細.更新者名
     *
     * @param 更新者名 the value for public.仕入データ明細.更新者名
     *
     * @mbg.generated Tue Oct 28 18:38:03 JST 2025
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }
}