package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 仕入先マスタ extends 仕入先マスタKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入先マスタ.仕入先名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 仕入先名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入先マスタ.仕入先名カナ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 仕入先名カナ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入先マスタ.仕入先担当者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 仕入先担当者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入先マスタ.仕入先部門名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 仕入先部門名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入先マスタ.仕入先郵便番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 仕入先郵便番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入先マスタ.仕入先都道府県
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 仕入先都道府県;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入先マスタ.仕入先住所１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 仕入先住所１;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入先マスタ.仕入先住所２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 仕入先住所２;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入先マスタ.仕入先電話番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 仕入先電話番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入先マスタ.仕入先ＦＡＸ番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 仕入先ｆａｘ番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入先マスタ.仕入先メールアドレス
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 仕入先メールアドレス;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入先マスタ.仕入先締日
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private Integer 仕入先締日;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入先マスタ.仕入先支払月
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private Integer 仕入先支払月;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入先マスタ.仕入先支払日
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private Integer 仕入先支払日;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入先マスタ.仕入先支払方法
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private Integer 仕入先支払方法;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入先マスタ.作成日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入先マスタ.作成者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入先マスタ.更新日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.仕入先マスタ.更新者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 更新者名;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入先マスタ.仕入先名
     *
     * @return the value of public.仕入先マスタ.仕入先名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get仕入先名() {
        return 仕入先名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入先マスタ.仕入先名
     *
     * @param 仕入先名 the value for public.仕入先マスタ.仕入先名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set仕入先名(String 仕入先名) {
        this.仕入先名 = 仕入先名 == null ? null : 仕入先名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入先マスタ.仕入先名カナ
     *
     * @return the value of public.仕入先マスタ.仕入先名カナ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get仕入先名カナ() {
        return 仕入先名カナ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入先マスタ.仕入先名カナ
     *
     * @param 仕入先名カナ the value for public.仕入先マスタ.仕入先名カナ
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set仕入先名カナ(String 仕入先名カナ) {
        this.仕入先名カナ = 仕入先名カナ == null ? null : 仕入先名カナ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入先マスタ.仕入先担当者名
     *
     * @return the value of public.仕入先マスタ.仕入先担当者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get仕入先担当者名() {
        return 仕入先担当者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入先マスタ.仕入先担当者名
     *
     * @param 仕入先担当者名 the value for public.仕入先マスタ.仕入先担当者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set仕入先担当者名(String 仕入先担当者名) {
        this.仕入先担当者名 = 仕入先担当者名 == null ? null : 仕入先担当者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入先マスタ.仕入先部門名
     *
     * @return the value of public.仕入先マスタ.仕入先部門名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get仕入先部門名() {
        return 仕入先部門名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入先マスタ.仕入先部門名
     *
     * @param 仕入先部門名 the value for public.仕入先マスタ.仕入先部門名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set仕入先部門名(String 仕入先部門名) {
        this.仕入先部門名 = 仕入先部門名 == null ? null : 仕入先部門名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入先マスタ.仕入先郵便番号
     *
     * @return the value of public.仕入先マスタ.仕入先郵便番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get仕入先郵便番号() {
        return 仕入先郵便番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入先マスタ.仕入先郵便番号
     *
     * @param 仕入先郵便番号 the value for public.仕入先マスタ.仕入先郵便番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set仕入先郵便番号(String 仕入先郵便番号) {
        this.仕入先郵便番号 = 仕入先郵便番号 == null ? null : 仕入先郵便番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入先マスタ.仕入先都道府県
     *
     * @return the value of public.仕入先マスタ.仕入先都道府県
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get仕入先都道府県() {
        return 仕入先都道府県;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入先マスタ.仕入先都道府県
     *
     * @param 仕入先都道府県 the value for public.仕入先マスタ.仕入先都道府県
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set仕入先都道府県(String 仕入先都道府県) {
        this.仕入先都道府県 = 仕入先都道府県 == null ? null : 仕入先都道府県.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入先マスタ.仕入先住所１
     *
     * @return the value of public.仕入先マスタ.仕入先住所１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get仕入先住所１() {
        return 仕入先住所１;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入先マスタ.仕入先住所１
     *
     * @param 仕入先住所１ the value for public.仕入先マスタ.仕入先住所１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set仕入先住所１(String 仕入先住所１) {
        this.仕入先住所１ = 仕入先住所１ == null ? null : 仕入先住所１.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入先マスタ.仕入先住所２
     *
     * @return the value of public.仕入先マスタ.仕入先住所２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get仕入先住所２() {
        return 仕入先住所２;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入先マスタ.仕入先住所２
     *
     * @param 仕入先住所２ the value for public.仕入先マスタ.仕入先住所２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set仕入先住所２(String 仕入先住所２) {
        this.仕入先住所２ = 仕入先住所２ == null ? null : 仕入先住所２.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入先マスタ.仕入先電話番号
     *
     * @return the value of public.仕入先マスタ.仕入先電話番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get仕入先電話番号() {
        return 仕入先電話番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入先マスタ.仕入先電話番号
     *
     * @param 仕入先電話番号 the value for public.仕入先マスタ.仕入先電話番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set仕入先電話番号(String 仕入先電話番号) {
        this.仕入先電話番号 = 仕入先電話番号 == null ? null : 仕入先電話番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入先マスタ.仕入先ＦＡＸ番号
     *
     * @return the value of public.仕入先マスタ.仕入先ＦＡＸ番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get仕入先ｆａｘ番号() {
        return 仕入先ｆａｘ番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入先マスタ.仕入先ＦＡＸ番号
     *
     * @param 仕入先ｆａｘ番号 the value for public.仕入先マスタ.仕入先ＦＡＸ番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set仕入先ｆａｘ番号(String 仕入先ｆａｘ番号) {
        this.仕入先ｆａｘ番号 = 仕入先ｆａｘ番号 == null ? null : 仕入先ｆａｘ番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入先マスタ.仕入先メールアドレス
     *
     * @return the value of public.仕入先マスタ.仕入先メールアドレス
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get仕入先メールアドレス() {
        return 仕入先メールアドレス;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入先マスタ.仕入先メールアドレス
     *
     * @param 仕入先メールアドレス the value for public.仕入先マスタ.仕入先メールアドレス
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set仕入先メールアドレス(String 仕入先メールアドレス) {
        this.仕入先メールアドレス = 仕入先メールアドレス == null ? null : 仕入先メールアドレス.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入先マスタ.仕入先締日
     *
     * @return the value of public.仕入先マスタ.仕入先締日
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public Integer get仕入先締日() {
        return 仕入先締日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入先マスタ.仕入先締日
     *
     * @param 仕入先締日 the value for public.仕入先マスタ.仕入先締日
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set仕入先締日(Integer 仕入先締日) {
        this.仕入先締日 = 仕入先締日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入先マスタ.仕入先支払月
     *
     * @return the value of public.仕入先マスタ.仕入先支払月
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public Integer get仕入先支払月() {
        return 仕入先支払月;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入先マスタ.仕入先支払月
     *
     * @param 仕入先支払月 the value for public.仕入先マスタ.仕入先支払月
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set仕入先支払月(Integer 仕入先支払月) {
        this.仕入先支払月 = 仕入先支払月;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入先マスタ.仕入先支払日
     *
     * @return the value of public.仕入先マスタ.仕入先支払日
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public Integer get仕入先支払日() {
        return 仕入先支払日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入先マスタ.仕入先支払日
     *
     * @param 仕入先支払日 the value for public.仕入先マスタ.仕入先支払日
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set仕入先支払日(Integer 仕入先支払日) {
        this.仕入先支払日 = 仕入先支払日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入先マスタ.仕入先支払方法
     *
     * @return the value of public.仕入先マスタ.仕入先支払方法
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public Integer get仕入先支払方法() {
        return 仕入先支払方法;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入先マスタ.仕入先支払方法
     *
     * @param 仕入先支払方法 the value for public.仕入先マスタ.仕入先支払方法
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set仕入先支払方法(Integer 仕入先支払方法) {
        this.仕入先支払方法 = 仕入先支払方法;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入先マスタ.作成日時
     *
     * @return the value of public.仕入先マスタ.作成日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入先マスタ.作成日時
     *
     * @param 作成日時 the value for public.仕入先マスタ.作成日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入先マスタ.作成者名
     *
     * @return the value of public.仕入先マスタ.作成者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入先マスタ.作成者名
     *
     * @param 作成者名 the value for public.仕入先マスタ.作成者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入先マスタ.更新日時
     *
     * @return the value of public.仕入先マスタ.更新日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入先マスタ.更新日時
     *
     * @param 更新日時 the value for public.仕入先マスタ.更新日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.仕入先マスタ.更新者名
     *
     * @return the value of public.仕入先マスタ.更新者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.仕入先マスタ.更新者名
     *
     * @param 更新者名 the value for public.仕入先マスタ.更新者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }
}