package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 倉庫部門マスタKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.倉庫部門マスタ.倉庫コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 倉庫コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.倉庫部門マスタ.部門コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 部門コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.倉庫部門マスタ.開始日
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private LocalDateTime 開始日;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.倉庫部門マスタ.倉庫コード
     *
     * @return the value of public.倉庫部門マスタ.倉庫コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get倉庫コード() {
        return 倉庫コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.倉庫部門マスタ.倉庫コード
     *
     * @param 倉庫コード the value for public.倉庫部門マスタ.倉庫コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set倉庫コード(String 倉庫コード) {
        this.倉庫コード = 倉庫コード == null ? null : 倉庫コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.倉庫部門マスタ.部門コード
     *
     * @return the value of public.倉庫部門マスタ.部門コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get部門コード() {
        return 部門コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.倉庫部門マスタ.部門コード
     *
     * @param 部門コード the value for public.倉庫部門マスタ.部門コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set部門コード(String 部門コード) {
        this.部門コード = 部門コード == null ? null : 部門コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.倉庫部門マスタ.開始日
     *
     * @return the value of public.倉庫部門マスタ.開始日
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public LocalDateTime get開始日() {
        return 開始日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.倉庫部門マスタ.開始日
     *
     * @param 開始日 the value for public.倉庫部門マスタ.開始日
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set開始日(LocalDateTime 開始日) {
        this.開始日 = 開始日;
    }
}