package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 入金データ {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金データ.入金番号
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 入金番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金データ.入金日
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private LocalDateTime 入金日;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金データ.部門コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 部門コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金データ.開始日
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private LocalDateTime 開始日;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金データ.顧客コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 顧客コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金データ.顧客枝番
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private Integer 顧客枝番;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金データ.支払方法区分
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private Integer 支払方法区分;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金データ.入金口座コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 入金口座コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金データ.入金金額
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private Integer 入金金額;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金データ.消込金額
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private Integer 消込金額;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金データ.作成日時
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金データ.作成者名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金データ.更新日時
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金データ.更新者名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 更新者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金データ.プログラム更新日時
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private LocalDateTime プログラム更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.入金データ.更新プログラム名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    private String 更新プログラム名;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金データ.入金番号
     *
     * @return the value of public.入金データ.入金番号
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get入金番号() {
        return 入金番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金データ.入金番号
     *
     * @param 入金番号 the value for public.入金データ.入金番号
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set入金番号(String 入金番号) {
        this.入金番号 = 入金番号 == null ? null : 入金番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金データ.入金日
     *
     * @return the value of public.入金データ.入金日
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public LocalDateTime get入金日() {
        return 入金日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金データ.入金日
     *
     * @param 入金日 the value for public.入金データ.入金日
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set入金日(LocalDateTime 入金日) {
        this.入金日 = 入金日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金データ.部門コード
     *
     * @return the value of public.入金データ.部門コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get部門コード() {
        return 部門コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金データ.部門コード
     *
     * @param 部門コード the value for public.入金データ.部門コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set部門コード(String 部門コード) {
        this.部門コード = 部門コード == null ? null : 部門コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金データ.開始日
     *
     * @return the value of public.入金データ.開始日
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public LocalDateTime get開始日() {
        return 開始日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金データ.開始日
     *
     * @param 開始日 the value for public.入金データ.開始日
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set開始日(LocalDateTime 開始日) {
        this.開始日 = 開始日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金データ.顧客コード
     *
     * @return the value of public.入金データ.顧客コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get顧客コード() {
        return 顧客コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金データ.顧客コード
     *
     * @param 顧客コード the value for public.入金データ.顧客コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set顧客コード(String 顧客コード) {
        this.顧客コード = 顧客コード == null ? null : 顧客コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金データ.顧客枝番
     *
     * @return the value of public.入金データ.顧客枝番
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public Integer get顧客枝番() {
        return 顧客枝番;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金データ.顧客枝番
     *
     * @param 顧客枝番 the value for public.入金データ.顧客枝番
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set顧客枝番(Integer 顧客枝番) {
        this.顧客枝番 = 顧客枝番;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金データ.支払方法区分
     *
     * @return the value of public.入金データ.支払方法区分
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public Integer get支払方法区分() {
        return 支払方法区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金データ.支払方法区分
     *
     * @param 支払方法区分 the value for public.入金データ.支払方法区分
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set支払方法区分(Integer 支払方法区分) {
        this.支払方法区分 = 支払方法区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金データ.入金口座コード
     *
     * @return the value of public.入金データ.入金口座コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get入金口座コード() {
        return 入金口座コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金データ.入金口座コード
     *
     * @param 入金口座コード the value for public.入金データ.入金口座コード
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set入金口座コード(String 入金口座コード) {
        this.入金口座コード = 入金口座コード == null ? null : 入金口座コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金データ.入金金額
     *
     * @return the value of public.入金データ.入金金額
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public Integer get入金金額() {
        return 入金金額;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金データ.入金金額
     *
     * @param 入金金額 the value for public.入金データ.入金金額
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set入金金額(Integer 入金金額) {
        this.入金金額 = 入金金額;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金データ.消込金額
     *
     * @return the value of public.入金データ.消込金額
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public Integer get消込金額() {
        return 消込金額;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金データ.消込金額
     *
     * @param 消込金額 the value for public.入金データ.消込金額
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set消込金額(Integer 消込金額) {
        this.消込金額 = 消込金額;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金データ.作成日時
     *
     * @return the value of public.入金データ.作成日時
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金データ.作成日時
     *
     * @param 作成日時 the value for public.入金データ.作成日時
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金データ.作成者名
     *
     * @return the value of public.入金データ.作成者名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金データ.作成者名
     *
     * @param 作成者名 the value for public.入金データ.作成者名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金データ.更新日時
     *
     * @return the value of public.入金データ.更新日時
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金データ.更新日時
     *
     * @param 更新日時 the value for public.入金データ.更新日時
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金データ.更新者名
     *
     * @return the value of public.入金データ.更新者名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金データ.更新者名
     *
     * @param 更新者名 the value for public.入金データ.更新者名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金データ.プログラム更新日時
     *
     * @return the value of public.入金データ.プログラム更新日時
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public LocalDateTime getプログラム更新日時() {
        return プログラム更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金データ.プログラム更新日時
     *
     * @param プログラム更新日時 the value for public.入金データ.プログラム更新日時
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void setプログラム更新日時(LocalDateTime プログラム更新日時) {
        this.プログラム更新日時 = プログラム更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.入金データ.更新プログラム名
     *
     * @return the value of public.入金データ.更新プログラム名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public String get更新プログラム名() {
        return 更新プログラム名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.入金データ.更新プログラム名
     *
     * @param 更新プログラム名 the value for public.入金データ.更新プログラム名
     *
     * @mbg.generated Tue Jun 17 18:01:22 JST 2025
     */
    public void set更新プログラム名(String 更新プログラム名) {
        this.更新プログラム名 = 更新プログラム名 == null ? null : 更新プログラム名.trim();
    }
}