package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 出荷先マスタ extends 出荷先マスタKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.出荷先マスタ.出荷先名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 出荷先名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.出荷先マスタ.地域コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 地域コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.出荷先マスタ.出荷先郵便番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 出荷先郵便番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.出荷先マスタ.出荷先住所１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 出荷先住所１;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.出荷先マスタ.出荷先住所２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 出荷先住所２;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.出荷先マスタ.作成日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.出荷先マスタ.作成者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.出荷先マスタ.更新日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.出荷先マスタ.更新者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    private String 更新者名;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.出荷先マスタ.出荷先名
     *
     * @return the value of public.出荷先マスタ.出荷先名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get出荷先名() {
        return 出荷先名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.出荷先マスタ.出荷先名
     *
     * @param 出荷先名 the value for public.出荷先マスタ.出荷先名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set出荷先名(String 出荷先名) {
        this.出荷先名 = 出荷先名 == null ? null : 出荷先名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.出荷先マスタ.地域コード
     *
     * @return the value of public.出荷先マスタ.地域コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get地域コード() {
        return 地域コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.出荷先マスタ.地域コード
     *
     * @param 地域コード the value for public.出荷先マスタ.地域コード
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set地域コード(String 地域コード) {
        this.地域コード = 地域コード == null ? null : 地域コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.出荷先マスタ.出荷先郵便番号
     *
     * @return the value of public.出荷先マスタ.出荷先郵便番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get出荷先郵便番号() {
        return 出荷先郵便番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.出荷先マスタ.出荷先郵便番号
     *
     * @param 出荷先郵便番号 the value for public.出荷先マスタ.出荷先郵便番号
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set出荷先郵便番号(String 出荷先郵便番号) {
        this.出荷先郵便番号 = 出荷先郵便番号 == null ? null : 出荷先郵便番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.出荷先マスタ.出荷先住所１
     *
     * @return the value of public.出荷先マスタ.出荷先住所１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get出荷先住所１() {
        return 出荷先住所１;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.出荷先マスタ.出荷先住所１
     *
     * @param 出荷先住所１ the value for public.出荷先マスタ.出荷先住所１
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set出荷先住所１(String 出荷先住所１) {
        this.出荷先住所１ = 出荷先住所１ == null ? null : 出荷先住所１.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.出荷先マスタ.出荷先住所２
     *
     * @return the value of public.出荷先マスタ.出荷先住所２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get出荷先住所２() {
        return 出荷先住所２;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.出荷先マスタ.出荷先住所２
     *
     * @param 出荷先住所２ the value for public.出荷先マスタ.出荷先住所２
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set出荷先住所２(String 出荷先住所２) {
        this.出荷先住所２ = 出荷先住所２ == null ? null : 出荷先住所２.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.出荷先マスタ.作成日時
     *
     * @return the value of public.出荷先マスタ.作成日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.出荷先マスタ.作成日時
     *
     * @param 作成日時 the value for public.出荷先マスタ.作成日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.出荷先マスタ.作成者名
     *
     * @return the value of public.出荷先マスタ.作成者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.出荷先マスタ.作成者名
     *
     * @param 作成者名 the value for public.出荷先マスタ.作成者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.出荷先マスタ.更新日時
     *
     * @return the value of public.出荷先マスタ.更新日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.出荷先マスタ.更新日時
     *
     * @param 更新日時 the value for public.出荷先マスタ.更新日時
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.出荷先マスタ.更新者名
     *
     * @return the value of public.出荷先マスタ.更新者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.出荷先マスタ.更新者名
     *
     * @param 更新者名 the value for public.出荷先マスタ.更新者名
     *
     * @mbg.generated Tue Jan 07 18:37:28 JST 2025
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }
}