package com.example.sms.infrastructure.datasource.autogen.model;

public class 受注データ明細Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.受注データ明細.受注番号
     *
     * @mbg.generated Mon Feb 17 17:55:57 JST 2025
     */
    private String 受注番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.受注データ明細.受注行番号
     *
     * @mbg.generated Mon Feb 17 17:55:57 JST 2025
     */
    private Integer 受注行番号;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.受注データ明細.受注番号
     *
     * @return the value of public.受注データ明細.受注番号
     *
     * @mbg.generated Mon Feb 17 17:55:57 JST 2025
     */
    public String get受注番号() {
        return 受注番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.受注データ明細.受注番号
     *
     * @param 受注番号 the value for public.受注データ明細.受注番号
     *
     * @mbg.generated Mon Feb 17 17:55:57 JST 2025
     */
    public void set受注番号(String 受注番号) {
        this.受注番号 = 受注番号 == null ? null : 受注番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.受注データ明細.受注行番号
     *
     * @return the value of public.受注データ明細.受注行番号
     *
     * @mbg.generated Mon Feb 17 17:55:57 JST 2025
     */
    public Integer get受注行番号() {
        return 受注行番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.受注データ明細.受注行番号
     *
     * @param 受注行番号 the value for public.受注データ明細.受注行番号
     *
     * @mbg.generated Mon Feb 17 17:55:57 JST 2025
     */
    public void set受注行番号(Integer 受注行番号) {
        this.受注行番号 = 受注行番号;
    }
}