package com.example.sms.infrastructure.datasource.autogen.model;

public class 在庫データKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.在庫データ.倉庫コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 倉庫コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.在庫データ.商品コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 商品コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.在庫データ.ロット番号
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String ロット番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.在庫データ.在庫区分
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 在庫区分;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.在庫データ.良品区分
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 良品区分;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.在庫データ.倉庫コード
     *
     * @return the value of public.在庫データ.倉庫コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get倉庫コード() {
        return 倉庫コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.在庫データ.倉庫コード
     *
     * @param 倉庫コード the value for public.在庫データ.倉庫コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set倉庫コード(String 倉庫コード) {
        this.倉庫コード = 倉庫コード == null ? null : 倉庫コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.在庫データ.商品コード
     *
     * @return the value of public.在庫データ.商品コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get商品コード() {
        return 商品コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.在庫データ.商品コード
     *
     * @param 商品コード the value for public.在庫データ.商品コード
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set商品コード(String 商品コード) {
        this.商品コード = 商品コード == null ? null : 商品コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.在庫データ.ロット番号
     *
     * @return the value of public.在庫データ.ロット番号
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String getロット番号() {
        return ロット番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.在庫データ.ロット番号
     *
     * @param ロット番号 the value for public.在庫データ.ロット番号
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void setロット番号(String ロット番号) {
        this.ロット番号 = ロット番号 == null ? null : ロット番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.在庫データ.在庫区分
     *
     * @return the value of public.在庫データ.在庫区分
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get在庫区分() {
        return 在庫区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.在庫データ.在庫区分
     *
     * @param 在庫区分 the value for public.在庫データ.在庫区分
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set在庫区分(String 在庫区分) {
        this.在庫区分 = 在庫区分 == null ? null : 在庫区分.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.在庫データ.良品区分
     *
     * @return the value of public.在庫データ.良品区分
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get良品区分() {
        return 良品区分;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.在庫データ.良品区分
     *
     * @param 良品区分 the value for public.在庫データ.良品区分
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set良品区分(String 良品区分) {
        this.良品区分 = 良品区分 == null ? null : 良品区分.trim();
    }
}