package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 在庫データ extends 在庫データKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.在庫データ.実在庫数
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private Integer 実在庫数;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.在庫データ.有効在庫数
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private Integer 有効在庫数;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.在庫データ.最終出荷日
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private LocalDateTime 最終出荷日;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.在庫データ.作成日時
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.在庫データ.作成者名
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.在庫データ.更新日時
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.在庫データ.更新者名
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private String 更新者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.在庫データ.version
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.在庫データ.実在庫数
     *
     * @return the value of public.在庫データ.実在庫数
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public Integer get実在庫数() {
        return 実在庫数;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.在庫データ.実在庫数
     *
     * @param 実在庫数 the value for public.在庫データ.実在庫数
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set実在庫数(Integer 実在庫数) {
        this.実在庫数 = 実在庫数;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.在庫データ.有効在庫数
     *
     * @return the value of public.在庫データ.有効在庫数
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public Integer get有効在庫数() {
        return 有効在庫数;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.在庫データ.有効在庫数
     *
     * @param 有効在庫数 the value for public.在庫データ.有効在庫数
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set有効在庫数(Integer 有効在庫数) {
        this.有効在庫数 = 有効在庫数;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.在庫データ.最終出荷日
     *
     * @return the value of public.在庫データ.最終出荷日
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public LocalDateTime get最終出荷日() {
        return 最終出荷日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.在庫データ.最終出荷日
     *
     * @param 最終出荷日 the value for public.在庫データ.最終出荷日
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set最終出荷日(LocalDateTime 最終出荷日) {
        this.最終出荷日 = 最終出荷日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.在庫データ.作成日時
     *
     * @return the value of public.在庫データ.作成日時
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.在庫データ.作成日時
     *
     * @param 作成日時 the value for public.在庫データ.作成日時
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.在庫データ.作成者名
     *
     * @return the value of public.在庫データ.作成者名
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.在庫データ.作成者名
     *
     * @param 作成者名 the value for public.在庫データ.作成者名
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.在庫データ.更新日時
     *
     * @return the value of public.在庫データ.更新日時
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.在庫データ.更新日時
     *
     * @param 更新日時 the value for public.在庫データ.更新日時
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.在庫データ.更新者名
     *
     * @return the value of public.在庫データ.更新者名
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.在庫データ.更新者名
     *
     * @param 更新者名 the value for public.在庫データ.更新者名
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.在庫データ.version
     *
     * @return the value of public.在庫データ.version
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.在庫データ.version
     *
     * @param version the value for public.在庫データ.version
     *
     * @mbg.generated Wed Sep 10 16:51:55 JST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}