package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 地域マスタ {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.地域マスタ.地域コード
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    private String 地域コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.地域マスタ.地域名
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    private String 地域名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.地域マスタ.作成日時
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.地域マスタ.作成者名
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.地域マスタ.更新日時
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.地域マスタ.更新者名
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    private String 更新者名;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.地域マスタ.地域コード
     *
     * @return the value of public.地域マスタ.地域コード
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    public String get地域コード() {
        return 地域コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.地域マスタ.地域コード
     *
     * @param 地域コード the value for public.地域マスタ.地域コード
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    public void set地域コード(String 地域コード) {
        this.地域コード = 地域コード == null ? null : 地域コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.地域マスタ.地域名
     *
     * @return the value of public.地域マスタ.地域名
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    public String get地域名() {
        return 地域名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.地域マスタ.地域名
     *
     * @param 地域名 the value for public.地域マスタ.地域名
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    public void set地域名(String 地域名) {
        this.地域名 = 地域名 == null ? null : 地域名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.地域マスタ.作成日時
     *
     * @return the value of public.地域マスタ.作成日時
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.地域マスタ.作成日時
     *
     * @param 作成日時 the value for public.地域マスタ.作成日時
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.地域マスタ.作成者名
     *
     * @return the value of public.地域マスタ.作成者名
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.地域マスタ.作成者名
     *
     * @param 作成者名 the value for public.地域マスタ.作成者名
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.地域マスタ.更新日時
     *
     * @return the value of public.地域マスタ.更新日時
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.地域マスタ.更新日時
     *
     * @param 更新日時 the value for public.地域マスタ.更新日時
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.地域マスタ.更新者名
     *
     * @return the value of public.地域マスタ.更新者名
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.地域マスタ.更新者名
     *
     * @param 更新者名 the value for public.地域マスタ.更新者名
     *
     * @mbg.generated Tue Jan 14 17:06:04 JST 2025
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }
}