package com.example.sms.infrastructure.datasource.autogen.model;

import java.time.LocalDateTime;

public class 発注データ明細 extends 発注データ明細Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ明細.発注行表示番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private Integer 発注行表示番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ明細.受注番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private String 受注番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ明細.受注行番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private Integer 受注行番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ明細.商品コード
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private String 商品コード;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ明細.商品名
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private String 商品名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ明細.発注単価
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private Integer 発注単価;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ明細.発注数量
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private Integer 発注数量;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ明細.入荷数量
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private Integer 入荷数量;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ明細.完了フラグ
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private Integer 完了フラグ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ明細.作成日時
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private LocalDateTime 作成日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ明細.作成者名
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private String 作成者名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ明細.更新日時
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private LocalDateTime 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.発注データ明細.更新者名
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    private String 更新者名;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ明細.発注行表示番号
     *
     * @return the value of public.発注データ明細.発注行表示番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public Integer get発注行表示番号() {
        return 発注行表示番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ明細.発注行表示番号
     *
     * @param 発注行表示番号 the value for public.発注データ明細.発注行表示番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set発注行表示番号(Integer 発注行表示番号) {
        this.発注行表示番号 = 発注行表示番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ明細.受注番号
     *
     * @return the value of public.発注データ明細.受注番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public String get受注番号() {
        return 受注番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ明細.受注番号
     *
     * @param 受注番号 the value for public.発注データ明細.受注番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set受注番号(String 受注番号) {
        this.受注番号 = 受注番号 == null ? null : 受注番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ明細.受注行番号
     *
     * @return the value of public.発注データ明細.受注行番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public Integer get受注行番号() {
        return 受注行番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ明細.受注行番号
     *
     * @param 受注行番号 the value for public.発注データ明細.受注行番号
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set受注行番号(Integer 受注行番号) {
        this.受注行番号 = 受注行番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ明細.商品コード
     *
     * @return the value of public.発注データ明細.商品コード
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public String get商品コード() {
        return 商品コード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ明細.商品コード
     *
     * @param 商品コード the value for public.発注データ明細.商品コード
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set商品コード(String 商品コード) {
        this.商品コード = 商品コード == null ? null : 商品コード.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ明細.商品名
     *
     * @return the value of public.発注データ明細.商品名
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public String get商品名() {
        return 商品名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ明細.商品名
     *
     * @param 商品名 the value for public.発注データ明細.商品名
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set商品名(String 商品名) {
        this.商品名 = 商品名 == null ? null : 商品名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ明細.発注単価
     *
     * @return the value of public.発注データ明細.発注単価
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public Integer get発注単価() {
        return 発注単価;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ明細.発注単価
     *
     * @param 発注単価 the value for public.発注データ明細.発注単価
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set発注単価(Integer 発注単価) {
        this.発注単価 = 発注単価;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ明細.発注数量
     *
     * @return the value of public.発注データ明細.発注数量
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public Integer get発注数量() {
        return 発注数量;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ明細.発注数量
     *
     * @param 発注数量 the value for public.発注データ明細.発注数量
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set発注数量(Integer 発注数量) {
        this.発注数量 = 発注数量;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ明細.入荷数量
     *
     * @return the value of public.発注データ明細.入荷数量
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public Integer get入荷数量() {
        return 入荷数量;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ明細.入荷数量
     *
     * @param 入荷数量 the value for public.発注データ明細.入荷数量
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set入荷数量(Integer 入荷数量) {
        this.入荷数量 = 入荷数量;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ明細.完了フラグ
     *
     * @return the value of public.発注データ明細.完了フラグ
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public Integer get完了フラグ() {
        return 完了フラグ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ明細.完了フラグ
     *
     * @param 完了フラグ the value for public.発注データ明細.完了フラグ
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set完了フラグ(Integer 完了フラグ) {
        this.完了フラグ = 完了フラグ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ明細.作成日時
     *
     * @return the value of public.発注データ明細.作成日時
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public LocalDateTime get作成日時() {
        return 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ明細.作成日時
     *
     * @param 作成日時 the value for public.発注データ明細.作成日時
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set作成日時(LocalDateTime 作成日時) {
        this.作成日時 = 作成日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ明細.作成者名
     *
     * @return the value of public.発注データ明細.作成者名
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public String get作成者名() {
        return 作成者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ明細.作成者名
     *
     * @param 作成者名 the value for public.発注データ明細.作成者名
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set作成者名(String 作成者名) {
        this.作成者名 = 作成者名 == null ? null : 作成者名.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ明細.更新日時
     *
     * @return the value of public.発注データ明細.更新日時
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public LocalDateTime get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ明細.更新日時
     *
     * @param 更新日時 the value for public.発注データ明細.更新日時
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set更新日時(LocalDateTime 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.発注データ明細.更新者名
     *
     * @return the value of public.発注データ明細.更新者名
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public String get更新者名() {
        return 更新者名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.発注データ明細.更新者名
     *
     * @param 更新者名 the value for public.発注データ明細.更新者名
     *
     * @mbg.generated Thu Aug 14 18:06:36 JST 2025
     */
    public void set更新者名(String 更新者名) {
        this.更新者名 = 更新者名 == null ? null : 更新者名.trim();
    }
}