package com.example.sms.infrastructure.datasource.autogen.model;

public class 請求データ明細Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.請求データ明細.請求番号
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    private String 請求番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.請求データ明細.売上番号
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    private String 売上番号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.請求データ明細.売上行番号
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    private Integer 売上行番号;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.請求データ明細.請求番号
     *
     * @return the value of public.請求データ明細.請求番号
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    public String get請求番号() {
        return 請求番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.請求データ明細.請求番号
     *
     * @param 請求番号 the value for public.請求データ明細.請求番号
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    public void set請求番号(String 請求番号) {
        this.請求番号 = 請求番号 == null ? null : 請求番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.請求データ明細.売上番号
     *
     * @return the value of public.請求データ明細.売上番号
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    public String get売上番号() {
        return 売上番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.請求データ明細.売上番号
     *
     * @param 売上番号 the value for public.請求データ明細.売上番号
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    public void set売上番号(String 売上番号) {
        this.売上番号 = 売上番号 == null ? null : 売上番号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.請求データ明細.売上行番号
     *
     * @return the value of public.請求データ明細.売上行番号
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    public Integer get売上行番号() {
        return 売上行番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.請求データ明細.売上行番号
     *
     * @param 売上行番号 the value for public.請求データ明細.売上行番号
     *
     * @mbg.generated Thu May 15 14:13:50 JST 2025
     */
    public void set売上行番号(Integer 売上行番号) {
        this.売上行番号 = 売上行番号;
    }
}